// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
// ** Copyright UCAR (c) 1992 - 2015
// ** University Corporation for Atmospheric Research(UCAR)
// ** National Center for Atmospheric Research(NCAR)
// ** Research Applications Laboratory(RAL)
// ** P.O.Box 3000, Boulder, Colorado, 80307-3000, USA
// ** See LICENCE.TXT if applicable for licence details
// ** 2015/00/12 23:54:29 UTC
// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
////////////////////////////////////////////
// Params.cc
//
// TDRP C++ code file for class 'Params'.
//
// Code for program derive_vars
//
// This file has been automatically
// generated by TDRP, do not modify.
//
/////////////////////////////////////////////

/**
 *
 * @file Params.cc
 *
 * @class Params
 *
 * This class is automatically generated by the Table
 * Driven Runtime Parameters (TDRP) system
 *
 * @note Source is automatically generated from
 *       paramdef file at compile time, do not modify
 *       since modifications will be overwritten.
 *
 *
 * @author Automatically generated
 *
 */
using namespace std;

#include "Params.hh"
#include <cstring>

  ////////////////////////////////////////////
  // Default constructor
  //

  Params::Params()

  {

    // zero out table

    memset(_table, 0, sizeof(_table));

    // zero out members

    memset(&_start_, 0, &_end_ - &_start_);

    // class name

    _className = "Params";

    // initialize table

    _init();

    // set members

    tdrpTable2User(_table, &_start_);

    _exitDeferred = false;

  }

  ////////////////////////////////////////////
  // Copy constructor
  //

  Params::Params(const Params& source)

  {

    // sync the source object

    source.sync();

    // zero out table

    memset(_table, 0, sizeof(_table));

    // zero out members

    memset(&_start_, 0, &_end_ - &_start_);

    // class name

    _className = "Params";

    // copy table

    tdrpCopyTable((TDRPtable *) source._table, _table);

    // set members

    tdrpTable2User(_table, &_start_);

    _exitDeferred = false;

  }

  ////////////////////////////////////////////
  // Destructor
  //

  Params::~Params()

  {

    // free up

    freeAll();

  }

  ////////////////////////////////////////////
  // Assignment
  //

  void Params::operator=(const Params& other)

  {

    // sync the other object

    other.sync();

    // free up any existing memory

    freeAll();

    // zero out table

    memset(_table, 0, sizeof(_table));

    // zero out members

    memset(&_start_, 0, &_end_ - &_start_);

    // copy table

    tdrpCopyTable((TDRPtable *) other._table, _table);

    // set members

    tdrpTable2User(_table, &_start_);

    _exitDeferred = other._exitDeferred;

  }

  ////////////////////////////////////////////
  // loadFromArgs()
  //
  // Loads up TDRP using the command line args.
  //
  // Check usage() for command line actions associated with
  // this function.
  //
  //   argc, argv: command line args
  //
  //   char **override_list: A null-terminated list of overrides
  //     to the parameter file.
  //     An override string has exactly the format of an entry
  //     in the parameter file itself.
  //
  //   char **params_path_p:
  //     If this is non-NULL, it is set to point to the path
  //     of the params file used.
  //
  //   bool defer_exit: normally, if the command args contain a 
  //      print or check request, this function will call exit().
  //      If defer_exit is set, such an exit is deferred and the
  //      private member _exitDeferred is set.
  //      Use exidDeferred() to test this flag.
  //
  //  Returns 0 on success, -1 on failure.
  //

  int Params::loadFromArgs(int argc, char **argv,
                           char **override_list,
                           char **params_path_p,
                           bool defer_exit)
  {
    int exit_deferred;
    if (_tdrpLoadFromArgs(argc, argv,
                          _table, &_start_,
                          override_list, params_path_p,
                          _className,
                          defer_exit, &exit_deferred)) {
      return (-1);
    } else {
      if (exit_deferred) {
        _exitDeferred = true;
      }
      return (0);
    }
  }

  ////////////////////////////////////////////
  // loadApplyArgs()
  //
  // Loads up TDRP using the params path passed in, and applies
  // the command line args for printing and checking.
  //
  // Check usage() for command line actions associated with
  // this function.
  //
  //   const char *param_file_path: the parameter file to be read in
  //
  //   argc, argv: command line args
  //
  //   char **override_list: A null-terminated list of overrides
  //     to the parameter file.
  //     An override string has exactly the format of an entry
  //     in the parameter file itself.
  //
  //   bool defer_exit: normally, if the command args contain a 
  //      print or check request, this function will call exit().
  //      If defer_exit is set, such an exit is deferred and the
  //      private member _exitDeferred is set.
  //      Use exidDeferred() to test this flag.
  //
  //  Returns 0 on success, -1 on failure.
  //

  int Params::loadApplyArgs(const char *params_path,
                            int argc, char **argv,
                            char **override_list,
                            bool defer_exit)
  {
    int exit_deferred;
    if (tdrpLoadApplyArgs(params_path, argc, argv,
                          _table, &_start_,
                          override_list,
                          _className,
                          defer_exit, &exit_deferred)) {
      return (-1);
    } else {
      if (exit_deferred) {
        _exitDeferred = true;
      }
      return (0);
    }
  }

  ////////////////////////////////////////////
  // isArgValid()
  // 
  // Check if a command line arg is a valid TDRP arg.
  //

  bool Params::isArgValid(const char *arg)
  {
    return (tdrpIsArgValid(arg));
  }

  ////////////////////////////////////////////
  // load()
  //
  // Loads up TDRP for a given class.
  //
  // This version of load gives the programmer the option to load
  // up more than one class for a single application. It is a
  // lower-level routine than loadFromArgs, and hence more
  // flexible, but the programmer must do more work.
  //
  //   const char *param_file_path: the parameter file to be read in.
  //
  //   char **override_list: A null-terminated list of overrides
  //     to the parameter file.
  //     An override string has exactly the format of an entry
  //     in the parameter file itself.
  //
  //   expand_env: flag to control environment variable
  //               expansion during tokenization.
  //               If TRUE, environment expansion is set on.
  //               If FALSE, environment expansion is set off.
  //
  //  Returns 0 on success, -1 on failure.
  //

  int Params::load(const char *param_file_path,
                   char **override_list,
                   int expand_env, int debug)
  {
    if (tdrpLoad(param_file_path,
                 _table, &_start_,
                 override_list,
                 expand_env, debug)) {
      return (-1);
    } else {
      return (0);
    }
  }

  ////////////////////////////////////////////
  // loadFromBuf()
  //
  // Loads up TDRP for a given class.
  //
  // This version of load gives the programmer the option to
  // load up more than one module for a single application,
  // using buffers which have been read from a specified source.
  //
  //   const char *param_source_str: a string which describes the
  //     source of the parameter information. It is used for
  //     error reporting only.
  //
  //   char **override_list: A null-terminated list of overrides
  //     to the parameter file.
  //     An override string has exactly the format of an entry
  //     in the parameter file itself.
  //
  //   const char *inbuf: the input buffer
  //
  //   int inlen: length of the input buffer
  //
  //   int start_line_num: the line number in the source which
  //     corresponds to the start of the buffer.
  //
  //   expand_env: flag to control environment variable
  //               expansion during tokenization.
  //               If TRUE, environment expansion is set on.
  //               If FALSE, environment expansion is set off.
  //
  //  Returns 0 on success, -1 on failure.
  //

  int Params::loadFromBuf(const char *param_source_str,
                          char **override_list,
                          const char *inbuf, int inlen,
                          int start_line_num,
                          int expand_env, int debug)
  {
    if (tdrpLoadFromBuf(param_source_str,
                        _table, &_start_,
                        override_list,
                        inbuf, inlen, start_line_num,
                        expand_env, debug)) {
      return (-1);
    } else {
      return (0);
    }
  }

  ////////////////////////////////////////////
  // loadDefaults()
  //
  // Loads up default params for a given class.
  //
  // See load() for more detailed info.
  //
  //  Returns 0 on success, -1 on failure.
  //

  int Params::loadDefaults(int expand_env)
  {
    if (tdrpLoad(NULL,
                 _table, &_start_,
                 NULL, expand_env, FALSE)) {
      return (-1);
    } else {
      return (0);
    }
  }

  ////////////////////////////////////////////
  // sync()
  //
  // Syncs the user struct data back into the parameter table,
  // in preparation for printing.
  //
  // This function alters the table in a consistent manner.
  // Therefore it can be regarded as const.
  //

  void Params::sync(void) const
  {
    tdrpUser2Table(_table, (char *) &_start_);
  }

  ////////////////////////////////////////////
  // print()
  // 
  // Print params file
  //
  // The modes supported are:
  //
  //   PRINT_SHORT:   main comments only, no help or descriptions
  //                  structs and arrays on a single line
  //   PRINT_NORM:    short + descriptions and help
  //   PRINT_LONG:    norm  + arrays and structs expanded
  //   PRINT_VERBOSE: long  + private params included
  //

  void Params::print(FILE *out, tdrp_print_mode_t mode)
  {
    tdrpPrint(out, _table, _className, mode);
  }

  ////////////////////////////////////////////
  // checkAllSet()
  //
  // Return TRUE if all set, FALSE if not.
  //
  // If out is non-NULL, prints out warning messages for those
  // parameters which are not set.
  //

  int Params::checkAllSet(FILE *out)
  {
    return (tdrpCheckAllSet(out, _table, &_start_));
  }

  //////////////////////////////////////////////////////////////
  // checkIsSet()
  //
  // Return TRUE if parameter is set, FALSE if not.
  //
  //

  int Params::checkIsSet(const char *paramName)
  {
    return (tdrpCheckIsSet(paramName, _table, &_start_));
  }

  ////////////////////////////////////////////
  // freeAll()
  //
  // Frees up all TDRP dynamic memory.
  //

  void Params::freeAll(void)
  {
    tdrpFreeAll(_table, &_start_);
  }

  ////////////////////////////////////////////
  // usage()
  //
  // Prints out usage message for TDRP args as passed
  // in to loadFromArgs().
  //

  void Params::usage(ostream &out)
  {
    out << "TDRP args: [options as below]\n"
        << "   [ -params/--params path ] specify params file path\n"
        << "   [ -check_params] check which params are not set\n"
        << "   [ -print_params [mode]] print parameters\n"
        << "     using following modes, default mode is 'norm'\n"
        << "       short:   main comments only, no help or descr\n"
        << "                structs and arrays on a single line\n"
        << "       norm:    short + descriptions and help\n"
        << "       long:    norm  + arrays and structs expanded\n"
        << "       verbose: long  + private params included\n"
        << "       short_expand:   short with env vars expanded\n"
        << "       norm_expand:    norm with env vars expanded\n"
        << "       long_expand:    long with env vars expanded\n"
        << "       verbose_expand: verbose with env vars expanded\n"
        << "   [ -tdrp_debug] debugging prints for tdrp\n"
        << "   [ -tdrp_usage] print this usage\n";
  }

  ////////////////////////////////////////////
  // arrayRealloc()
  //
  // Realloc 1D array.
  //
  // If size is increased, the values from the last array 
  // entry is copied into the new space.
  //
  // Returns 0 on success, -1 on error.
  //

  int Params::arrayRealloc(const char *param_name, int new_array_n)
  {
    if (tdrpArrayRealloc(_table, &_start_,
                         param_name, new_array_n)) {
      return (-1);
    } else {
      return (0);
    }
  }

  ////////////////////////////////////////////
  // array2DRealloc()
  //
  // Realloc 2D array.
  //
  // If size is increased, the values from the last array 
  // entry is copied into the new space.
  //
  // Returns 0 on success, -1 on error.
  //

  int Params::array2DRealloc(const char *param_name,
                             int new_array_n1,
                             int new_array_n2)
  {
    if (tdrpArray2DRealloc(_table, &_start_, param_name,
                           new_array_n1, new_array_n2)) {
      return (-1);
    } else {
      return (0);
    }
  }

  ////////////////////////////////////////////
  // _init()
  //
  // Class table initialization function.
  //
  //

  void Params::_init()

  {

    TDRPtable *tt = _table;

    // Parameter 'fcst_var_names'
    // ctype is 'char*'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = STRING_TYPE;
    tt->param_name = tdrpStrDup("fcst_var_names");
    tt->descr = tdrpStrDup("Forecast variables");
    tt->help = tdrpStrDup("Variables which need to be copied over to output file");
    tt->array_offset = (char *) &_fcst_var_names - &_start_;
    tt->array_n_offset = (char *) &fcst_var_names_n - &_start_;
    tt->is_array = TRUE;
    tt->array_len_fixed = FALSE;
    tt->array_elem_size = sizeof(char*);
    tt->array_n = 30;
    tt->array_vals = (tdrpVal_t *)
        tdrpMalloc(tt->array_n * sizeof(tdrpVal_t));
      tt->array_vals[0].s = tdrpStrDup("T");
      tt->array_vals[1].s = tdrpStrDup("max_T");
      tt->array_vals[2].s = tdrpStrDup("min_T");
      tt->array_vals[3].s = tdrpStrDup("dewpt");
      tt->array_vals[4].s = tdrpStrDup("wind_u");
      tt->array_vals[5].s = tdrpStrDup("wind_v");
      tt->array_vals[6].s = tdrpStrDup("wind_speed");
      tt->array_vals[7].s = tdrpStrDup("cloud_cov");
      tt->array_vals[8].s = tdrpStrDup("visibility");
      tt->array_vals[9].s = tdrpStrDup("prob_fog");
      tt->array_vals[10].s = tdrpStrDup("prob_thunder");
      tt->array_vals[11].s = tdrpStrDup("cprob_rain");
      tt->array_vals[12].s = tdrpStrDup("cprob_snow");
      tt->array_vals[13].s = tdrpStrDup("cprob_ice");
      tt->array_vals[14].s = tdrpStrDup("prob_precip03");
      tt->array_vals[15].s = tdrpStrDup("prob_precip06");
      tt->array_vals[16].s = tdrpStrDup("prob_precip24");
      tt->array_vals[17].s = tdrpStrDup("qpf03");
      tt->array_vals[18].s = tdrpStrDup("qpf06");
      tt->array_vals[19].s = tdrpStrDup("P_sfc");
      tt->array_vals[20].s = tdrpStrDup("T_cb");
      tt->array_vals[21].s = tdrpStrDup("T_bls");
      tt->array_vals[22].s = tdrpStrDup("T_lbls0");
      tt->array_vals[23].s = tdrpStrDup("T_lbls1");
      tt->array_vals[24].s = tdrpStrDup("T_lbls2");
      tt->array_vals[25].s = tdrpStrDup("T_lbls3");
      tt->array_vals[26].s = tdrpStrDup("snow_depth");
      tt->array_vals[27].s = tdrpStrDup("cloud_low");
      tt->array_vals[28].s = tdrpStrDup("cloud_middle");
      tt->array_vals[29].s = tdrpStrDup("cloud_high");
    tt++;
    
    // Parameter 'derived_var_names'
    // ctype is 'char*'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = STRING_TYPE;
    tt->param_name = tdrpStrDup("derived_var_names");
    tt->descr = tdrpStrDup("Derived variables");
    tt->help = tdrpStrDup("Variables which need to be derived from forecast variables");
    tt->array_offset = (char *) &_derived_var_names - &_start_;
    tt->array_n_offset = (char *) &derived_var_names_n - &_start_;
    tt->is_array = TRUE;
    tt->array_len_fixed = FALSE;
    tt->array_elem_size = sizeof(char*);
    tt->array_n = 21;
    tt->array_vals = (tdrpVal_t *)
        tdrpMalloc(tt->array_n * sizeof(tdrpVal_t));
      tt->array_vals[0].s = tdrpStrDup("prob_precip01");
      tt->array_vals[1].s = tdrpStrDup("qpf01");
      tt->array_vals[2].s = tdrpStrDup("wind_dir");
      tt->array_vals[3].s = tdrpStrDup("wind_speed_mph");
      tt->array_vals[4].s = tdrpStrDup("rh");
      tt->array_vals[5].s = tdrpStrDup("rh_pct");
      tt->array_vals[6].s = tdrpStrDup("TempF");
      tt->array_vals[7].s = tdrpStrDup("dewptF");
      tt->array_vals[8].s = tdrpStrDup("precip_rate");
      tt->array_vals[9].s = tdrpStrDup("precip_rate_inches");
      tt->array_vals[10].s = tdrpStrDup("precip_type");
      tt->array_vals[11].s = tdrpStrDup("precip_accum");
      tt->array_vals[12].s = tdrpStrDup("precip_accum_inches");
      tt->array_vals[13].s = tdrpStrDup("snow_rate");
      tt->array_vals[14].s = tdrpStrDup("snow_rate_inches");
      tt->array_vals[15].s = tdrpStrDup("snow_accum_total");
      tt->array_vals[16].s = tdrpStrDup("snow_accum_total_inches");
      tt->array_vals[17].s = tdrpStrDup("snow_accum");
      tt->array_vals[18].s = tdrpStrDup("snow_accum_inches");
      tt->array_vals[19].s = tdrpStrDup("prob_precip03_pct");
      tt->array_vals[20].s = tdrpStrDup("blowing_snow_potential");
    tt++;
    
    // Parameter 'max_history'
    // ctype is 'long'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = LONG_TYPE;
    tt->param_name = tdrpStrDup("max_history");
    tt->descr = tdrpStrDup("Maximum history in days");
    tt->help = tdrpStrDup("Maximum number of days to allow for history used for blowing snow calculation");
    tt->val_offset = (char *) &max_history - &_start_;
    tt->single_val.l = 4;
    tt++;
    
    // Parameter 'pop_threshold'
    // ctype is 'float'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = FLOAT_TYPE;
    tt->param_name = tdrpStrDup("pop_threshold");
    tt->descr = tdrpStrDup("Probability of precipitation threshold");
    tt->help = tdrpStrDup("POP value which must be attained before declaring precipitation.");
    tt->val_offset = (char *) &pop_threshold - &_start_;
    tt->single_val.f = 0.25;
    tt++;
    
    // Parameter 'qpf_threshold'
    // ctype is 'float'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = FLOAT_TYPE;
    tt->param_name = tdrpStrDup("qpf_threshold");
    tt->descr = tdrpStrDup("Quantitative precipitation forecast threshold");
    tt->help = tdrpStrDup("QPF value which must be attained before declaring precipitation.");
    tt->val_offset = (char *) &qpf_threshold - &_start_;
    tt->single_val.f = 0.05;
    tt++;
    
    // Parameter 'ice_threshold'
    // ctype is 'float'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = FLOAT_TYPE;
    tt->param_name = tdrpStrDup("ice_threshold");
    tt->descr = tdrpStrDup("Freezing precipitation threshold");
    tt->help = tdrpStrDup("CPOI value which must be attained before declaring freezing precipitation.");
    tt->val_offset = (char *) &ice_threshold - &_start_;
    tt->single_val.f = 0.25;
    tt++;
    
    // Parameter 'snow_threshold'
    // ctype is 'float'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = FLOAT_TYPE;
    tt->param_name = tdrpStrDup("snow_threshold");
    tt->descr = tdrpStrDup("Frozen (snow) precipitation threshold");
    tt->help = tdrpStrDup("CPOS value which must be attained before declaring frozen precipitation.");
    tt->val_offset = (char *) &snow_threshold - &_start_;
    tt->single_val.f = 0.4;
    tt++;
    
    // Parameter 'max_ts_tolerance'
    // ctype is 'float'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = FLOAT_TYPE;
    tt->param_name = tdrpStrDup("max_ts_tolerance");
    tt->descr = tdrpStrDup("Allowed difference between dicast (utc) max-T value and timeseries max-T (deg C)");
    tt->help = tdrpStrDup("If the dicast max-T is within this range of the timeseries, use the dicast value as is, otherwise use the time-series max plus the tolerance");
    tt->val_offset = (char *) &max_ts_tolerance - &_start_;
    tt->single_val.f = 1;
    tt++;
    
    // Parameter 'min_ts_tolerance'
    // ctype is 'float'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = FLOAT_TYPE;
    tt->param_name = tdrpStrDup("min_ts_tolerance");
    tt->descr = tdrpStrDup("Allowed difference between dicast (utc) min-T value and timeseries min-T (deg C)");
    tt->help = tdrpStrDup("If the dicast min-T is within this range of the timeseries, use the dicast value as is, otherwise use the time-series min minus the tolerance");
    tt->val_offset = (char *) &min_ts_tolerance - &_start_;
    tt->single_val.f = 2.5;
    tt++;
    
    // Parameter 'local_min_start'
    // ctype is 'int'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = INT_TYPE;
    tt->param_name = tdrpStrDup("local_min_start");
    tt->descr = tdrpStrDup("Offset from midnight to start looking for the daily local minimum temperature in the time-series");
    tt->help = tdrpStrDup("This is an integer value that can be negative or postive. For example: -5 is 7pm on the day before, 0 is 12am on the current day");
    tt->val_offset = (char *) &local_min_start - &_start_;
    tt->single_val.i = 0;
    tt++;
    
    // Parameter 'local_min_end'
    // ctype is 'int'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = INT_TYPE;
    tt->param_name = tdrpStrDup("local_min_end");
    tt->descr = tdrpStrDup("Offset from midnight to end looking for the daily local minimum temperature in the time-series");
    tt->help = tdrpStrDup("This is an integer value that can be negative or postive. For example: 8 is 8am on the current day, 24 is 11:59pm on the current day");
    tt->val_offset = (char *) &local_min_end - &_start_;
    tt->single_val.i = 24;
    tt++;
    
    // Parameter 'local_max_start'
    // ctype is 'int'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = INT_TYPE;
    tt->param_name = tdrpStrDup("local_max_start");
    tt->descr = tdrpStrDup("Offset from midnight to start looking for the daily local maximum temperature in the time-series");
    tt->help = tdrpStrDup("This is an integer value that can be negative or postive. For example: 7 is 7am on the current day, 0 is 12am on the current day");
    tt->val_offset = (char *) &local_max_start - &_start_;
    tt->single_val.i = 0;
    tt++;
    
    // Parameter 'local_max_end'
    // ctype is 'int'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = INT_TYPE;
    tt->param_name = tdrpStrDup("local_max_end");
    tt->descr = tdrpStrDup("Offset from midnight to end looking for the daily local maximum temperature in the time-series");
    tt->help = tdrpStrDup("This is an integer value that can be negative or postive. For example: 19 is 7pm on the current day, 24 is 11:59pm on the current day");
    tt->val_offset = (char *) &local_max_end - &_start_;
    tt->single_val.i = 24;
    tt++;
    
    // Parameter 'daytime_max_ts_tolerance'
    // ctype is 'float'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = FLOAT_TYPE;
    tt->param_name = tdrpStrDup("daytime_max_ts_tolerance");
    tt->descr = tdrpStrDup("Allowed difference between dicast (utc) max-T value and timeseries max-T (deg C)");
    tt->help = tdrpStrDup("If the dicast max-T is within this range of the timeseries, use the dicast value as is, otherwise use the time-series max plus the tolerance");
    tt->val_offset = (char *) &daytime_max_ts_tolerance - &_start_;
    tt->single_val.f = 1;
    tt++;
    
    // Parameter 'daytime_max_ts_correction'
    // ctype is 'float'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = FLOAT_TYPE;
    tt->param_name = tdrpStrDup("daytime_max_ts_correction");
    tt->descr = tdrpStrDup("Correction to dicast T timeseries if outside tolerence range (deg C)");
    tt->help = tdrpStrDup("If the dicast max-T is not within range of the timeseries plus tolerence, use the time-series min minus this correction");
    tt->val_offset = (char *) &daytime_max_ts_correction - &_start_;
    tt->single_val.f = 1;
    tt++;
    
    // Parameter 'nighttime_min_ts_tolerance'
    // ctype is 'float'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = FLOAT_TYPE;
    tt->param_name = tdrpStrDup("nighttime_min_ts_tolerance");
    tt->descr = tdrpStrDup("Allowed difference between dicast (utc) min-T value and timeseries min-T (deg C)");
    tt->help = tdrpStrDup("If the dicast min-T is not within range of the timeseries plus tolerence, use the time-series min minus this correction");
    tt->val_offset = (char *) &nighttime_min_ts_tolerance - &_start_;
    tt->single_val.f = 2.5;
    tt++;
    
    // Parameter 'nighttime_min_ts_correction'
    // ctype is 'float'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = FLOAT_TYPE;
    tt->param_name = tdrpStrDup("nighttime_min_ts_correction");
    tt->descr = tdrpStrDup("Correction to dicast T timeseries if outside tolerence range (deg C)");
    tt->help = tdrpStrDup("If the dicast min-T is within this range of the timeseries, use the dicast value as is, otherwise use the time-series min minus the tolerance");
    tt->val_offset = (char *) &nighttime_min_ts_correction - &_start_;
    tt->single_val.f = 0.8;
    tt++;
    
    // Parameter 'nighttime_min_start'
    // ctype is 'int'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = INT_TYPE;
    tt->param_name = tdrpStrDup("nighttime_min_start");
    tt->descr = tdrpStrDup("Offset from midnight to start looking for the daily nighttime minimum temperature in the time-series");
    tt->help = tdrpStrDup("This is an integer value that can be negative or postive. For example: -5 is 7pm on the day before, 0 is 12am on the current day");
    tt->val_offset = (char *) &nighttime_min_start - &_start_;
    tt->single_val.i = -6;
    tt++;
    
    // Parameter 'nighttime_min_end'
    // ctype is 'int'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = INT_TYPE;
    tt->param_name = tdrpStrDup("nighttime_min_end");
    tt->descr = tdrpStrDup("Offset from midnight to end looking for the daily nighttime minimum temperature in the time-series");
    tt->help = tdrpStrDup("This is an integer value that can be negative or postive. For example: 8 is 8am on the current day, 24 is 11:59pm on the current day");
    tt->val_offset = (char *) &nighttime_min_end - &_start_;
    tt->single_val.i = 8;
    tt++;
    
    // Parameter 'daytime_max_start'
    // ctype is 'int'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = INT_TYPE;
    tt->param_name = tdrpStrDup("daytime_max_start");
    tt->descr = tdrpStrDup("Offset from midnight to start looking for the daily daytime maximum temperature in the time-series");
    tt->help = tdrpStrDup("This is an integer value that can be negative or postive. For example: 7 is 7am on the current day, 0 is 12am on the current day");
    tt->val_offset = (char *) &daytime_max_start - &_start_;
    tt->single_val.i = 7;
    tt++;
    
    // Parameter 'daytime_max_end'
    // ctype is 'int'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = INT_TYPE;
    tt->param_name = tdrpStrDup("daytime_max_end");
    tt->descr = tdrpStrDup("Offset from midnight to end looking for the daily daytime maximum temperature in the time-series");
    tt->help = tdrpStrDup("This is an integer value that can be negative or postive. For example: 19 is 7pm on the current day, 24 is 11:59pm on the current day");
    tt->val_offset = (char *) &daytime_max_end - &_start_;
    tt->single_val.i = 19;
    tt++;
    
    // trailing entry has param_name set to NULL
    
    tt->param_name = NULL;
    
    return;
  
  }
