
import os

env = Environment(
        CPPPATH=[".", os.environ["NETCDF_INC_DIR"], os.environ["HDF_INC_DIR"], os.environ["LOCAL_INC_DIR"], os.environ["RAL_INC_DIR"]], 
        CCFLAGS=os.environ["RAL_CCFLAGS"], 
        LIBPATH=[os.environ["NETCDF_LIB_DIR"], os.environ["HDF_LIB_DIR"], os.environ["LOCAL_LIB_DIR"], os.environ["RAL_LIB_DIR"]] )

vdt_inc_dir = "%s/vdt4" % os.environ["LOCAL_INC_DIR"]

probe_message_dataset_manager = env.Program(
    "vdt4", [
    "arguments.cc",
    "config_reader.cc",
    "main.cc",
    "process.cc",
    "qc_check.cc",    
    "vdt_probe_data_qc.cc",
    "vdt_probe_message_datasets_test.cc",
    "vdt_probe_message_datasets.cc",
    "vdt_test_generator.cc"
                                   ],LIBS=[
                                           "libconfig++",
                                           "log",
                                           "rwx",
#                                           "gdal",
                                           "vdt4",
                                           "ANN",
                                           "netcdf_c++4",
                                           "netcdf_c++",
                                           "netcdf",
                                           "hdf5_hl",
                                           "hdf5",
                                           "z",
                                           "Proj4Wrap",
                                           "proj",
                                           "boost_filesystem",
                                           "boost_system",
                                           "stat_tools",
                                           "m"])

env.Install(os.environ["LOCAL_BIN_DIR"], "vdt4")
env.Alias("install", [os.environ["LOCAL_BIN_DIR"]])


