# For c-shell users: in you .cshrc set the following
# 
# on motown:
# setenv LOCAL_ROOT /d1/local
# setenv LOCAL_INC_DIR ${LOCAL_ROOT}/include
# setenv LOCAL_LIB_DIR ${LOCAL_ROOT}/lib
# setenv LOCAL_BIN_DIR ${LOCAL_ROOT}/bin
#
# setenv RAL_INC_DIR /usr/include
# setenv RAL_LIB_DIR /usr/lib
# setenv RAL_CCFLAGS "-Wall -g -O -static"

import os

env = Environment(
        CPPPATH=[".", os.environ["NETCDF_INC_DIR"], os.environ["HDF_INC_DIR"], os.environ["ZLIB_INC_DIR"], os.environ["LOCAL_INC_DIR"],os.environ["RAL_INC_DIR"]], 
        CCFLAGS=os.environ["RAL_CCFLAGS"], 
        LIBPATH=[os.environ["NETCDF_LIB_DIR"], os.environ["HDF_LIB_DIR"], os.environ["ZLIB_LIB_DIR"], os.environ["LOCAL_LIB_DIR"], os.environ["RAL_LIB_DIR"]] )

#vdt_inc_dir = "%s/vdt4" % os.environ["LOCAL_INC_DIR"]

cdf_to_csv = env.Program(
    "cdf_to_csv_dicast", [
    "main.cc",
    "arguments.cc",
    "process.cc",
    "config_reader.cc",
    "csv_writer.cc",
    "ncfc_utils.cc",
    "stat_utils.cc"
    ],
    LIBS=[
    "libconfig++",
    "log",
    "rwx",
    "vdt4",
    "ncfc",
    "ncf",
    "site_list",
    "netcdf_c++4",
    "netcdf_c++",
    "netcdf",
    "hdf5_hl",
    "hdf5",
    "z",
    "boost_filesystem",
    "boost_system"])

env.Install(os.environ["LOCAL_BIN_DIR"], "cdf_to_csv_dicast")
env.Alias("install", [os.environ["LOCAL_BIN_DIR"]])
