
import os


env = Environment(CPPPATH=['.', os.environ['LOCAL_INC_DIR']],
                  LIBPATH=[os.environ['LOCAL_LIB_DIR']],
                  CCFLAGS=os.environ['CCFLAGS'],
                  FORTRANFLAGS='-fdefault-integer-8')

    
env.Library('metro', [
    'global.c',
    'macadam.c',
    'array2matrix.f',
    'balanc.f',
    'constPhys.f',
    'coupla.f',
    'flxsurfz.f',
    'grille.f',
    'initial.f',
    'lib_gen.f',
    'lib_therm.f'
    ])

env.Install(os.environ['LOCAL_LIB_DIR'], 'libmetro.a')

install_include = '%s/metro' % os.environ['LOCAL_INC_DIR']
env.Install(install_include, [
    'global.h',
    'macadam.h',
    'number.h'
    ])

env.Alias('install', [os.environ['LOCAL_LIB_DIR'], install_include])
env.Alias('install_include', install_include)
