
import os
env = Environment(CPPPATH=[".", "/usr/include", os.environ["NETCDF_INC_DIR"], os.environ["HDF_INC_DIR"], os.environ["LOCAL_INC_DIR"], os.environ["RAL_INC_DIR"]], LIBPATH=["/usr/lib", os.environ["NETCDF_LIB_DIR"], os.environ["HDF_LIB_DIR"], os.environ["LOCAL_LIB_DIR"], os.environ["RAL_LIB_DIR"]], CCFLAGS=os.environ["RAL_CCFLAGS"])

env.Library("rwx", [
    "rwx_cdf_field_reader.cc",
    "rwx_cdf_field_writer.cc",
    "rwx_conversions.cc",
    "rwx_vector_collection.cc",
    "rwx_vector_collection_nc.cc",
    "rwx_rtma_dataset.cc",
    "rwx_road_segment_assessment.cc",
    "rwx_types.cc"
],

            LIBS=[
            "netcdf"
]
            )

env.Install(os.environ["LOCAL_LIB_DIR"], "librwx.a")

install_include = "%s/rwx" % os.environ["LOCAL_INC_DIR"]
env.Install(install_include, [
    "rwx_cdf_field_reader.hh",
    "rwx_cdf_field_writer.hh",
    "rwx_conversions.hh",
    "rwx_rtma_dataset.hh",
    "rwx_vector_collection.hh",
    "rwx_vector_collection_nc.hh",
    "rwx_road_segment_assessment.hh",
    "rwx_types.hh"
]

)

env.Alias("install", [os.environ["LOCAL_LIB_DIR"], install_include])
env.Alias("install_include", install_include)
