
import os
env = Environment(CPPPATH='./', LIBPATH=os.environ['LOCAL_LIB_DIR'], CCFLAGS=os.environ['CCFLAGS'])
    
env.Library('tdrp', [
    'check.c',
    'convert.c',
    'copy.c',
    'find_item.c',
    'load.c',
    'mem.c',
    'override.c',
    'print.c',
    'read_item.c',
    'tdrp.c',
    'tdrp_obsolete.c',
    'tdrpbuf.c',
    'token_list.c',
    'tokenize.c',
    'warn_on_extra_params.c',
    ])

env.Install(env['LIBPATH'], 'libtdrp.a')

install_include = '%s/tdrp' % os.environ['LOCAL_INC_DIR']
env.Install(install_include, [
    'tdrpbuf.h',
    'tdrp.h',
    'tdrp_obsolete.h',
    'tdrp_p.h'
    ])

env.Alias('install', [env['LIBPATH'], install_include])
env.Alias('install_include', install_include)
