
import os

env = Environment(CPPPATH=[os.environ["LOCAL_INC_DIR"], os.environ["RAL_INC_DIR"], os.environ["NETCDF_INC_DIR"], "include"], LIBPATH=[os.environ["LOCAL_LIB_DIR"], os.environ["RAL_LIB_DIR"], os.environ["NETCDF_LIB_DIR"]], CCFLAGS=os.environ["RAL_CCFLAGS"])
    
env.Library("ncfc", [
  "ncfc/var_input.cc",
  "ncfc/var_output.cc",
  "ncfc/get_unlim.cc",
  "ncfc/get_variables.cc",
  "ncfc/get_var_info.cc",
  "ncfc/get_var_list.cc",
  "ncfc/put_variables.cc",
  "ncfc/cdfinput.cc",
  "ncfc/make_cdf.cc",
  "ncfc/get_dims.cc"]
            )

env.Install(os.environ["LOCAL_LIB_DIR"], "libncfc.a")

install_include = "%s/ncfc" % os.environ["LOCAL_INC_DIR"]
env.Install(install_include, ["include/ncfc/ncfc.hh"])

env.Alias("install", [os.environ["LOCAL_LIB_DIR"], install_include])
env.Alias("install_include", install_include)





