
import os


env = Environment(CPPPATH=['.', os.environ['NETCDF_INC_DIR'],
                           os.environ['HDF_INC_DIR'],
                           os.environ['ZLIB_INC_DIR'],
                           os.environ['LOCAL_INC_DIR']],
                  LIBPATH=[os.environ['NETCDF_LIB_DIR'],
                           os.environ['HDF5_LIB_DIR'],
                           os.environ['ZLIB_LIB_DIR'],
                           os.environ['LOCAL_LIB_DIR']],
                  CCFLAGS=os.environ['CCFLAGS'])

    
env.Library('site_list', [
    'site_list.cc',
    'SiteList.cc',
    'SiteLoc.cc'
    ])

env.Install(os.environ['LOCAL_LIB_DIR'], 'libsite_list.a')

install_include = '%s/site_list' % os.environ['LOCAL_INC_DIR']
env.Install(install_include, [
    'site_list.hh',
    'SiteList.hh',
    'SiteLoc.hh'
])

env.Alias('install', [os.environ['LOCAL_LIB_DIR'], install_include])
env.Alias('install_include', install_include)
