
import os
env = Environment(CPPPATH=["include", os.environ["LOCAL_INC_DIR"]], LIBPATH=os.environ["RAL_LIB_DIR"], CCFLAGS=os.environ["RAL_CCFLAGS"])
    
env.Library("ncf", [
  "ncf/att_as_string.cc",
  "ncf/finite.cc",
  "ncf/cdltonc.cc",
  "ncf/cdf2unix_time.cc",
  "ncf/gtime.cc",
  "ncf/find_day_start.cc",
  "ncf/write_var.cc",
  "ncf/get_dim_size.cc",
  "ncf/get_var.cc",
  "ncf/get_var_attr.cc",
  "ncf/get_var_fill_val.cc",
  "ncf/put_var_attr.cc",
  "ncf/put_var.cc",
  "ncf/get_attr.cc",
  "ncf/put_attr.cc"])

env.Install(env["LIBPATH"], "libncf.a")

install_include = "%s/ncf" % os.environ["RAL_INC_DIR"]
env.Install(install_include, ["include/ncf/ncf.hh", "include/ncf/gtime.h", "include/ncf/ncf_template.hh"])

env.Alias("install", [env["LIBPATH"], install_include])
env.Alias("install_include", install_include)





