import os

# set the name of the application
program = 'create_nbr_list'

env = Environment(
        CPPPATH=['.', os.environ['LOCAL_INC_DIR'], os.environ['NETCDF_INC_DIR'],
                 os.environ['HDF_INC_DIR'], os.environ['ZLIB_INC_DIR']], 
        LIBPATH=[os.environ['LOCAL_LIB_DIR'], os.environ['NETCDF_LIB_DIR'],
                 os.environ['HDF5_LIB_DIR'], os.environ['ZLIB_LIB_DIR']],
        CCFLAGS=os.environ['CCFLAGS'])


env.Program(
    program,[
        Glob('*.cc')
        ],
    LIBS=[
        'log',
        'ncf',
        'nxncf',
        'site_list',
        'netcdf_c++',
        'netcdf',
        'hdf5_hl',
        'hdf5',
        'z'
        ],
    )

env.Install(os.environ['LOCAL_BIN_DIR'], program)
env.Alias('install', os.environ['LOCAL_BIN_DIR'])
