
import os
env = Environment(CPPPATH=[os.environ["NETCDF_INC_DIR"], "include", os.environ["RAL_INC_DIR"], os.environ["LOCAL_INC_DIR"]], LIBPATH=os.environ["RAL_LIB_DIR"], CCFLAGS=os.environ["RAL_CCFLAGS"])
    
env.Library("nxncf", [
    "nxncf/ncf_fcst_output.cc",
    "nxncf/ncf_site.cc",
    "nxncf/get_sites.cc",
    "nxncf/write_creation_time.cc",
    "nxncf/model_id.cc",
    "nxncf/create_index_array.cc"]
            )

env.Install(env["LIBPATH"], "libnxncf.a")

install_include = "%s/nxncf" % os.environ["RAL_INC_DIR"]
env.Install(install_include, ["include/nxncf/nxncf.hh"])

env.Alias("install", [env["LIBPATH"], install_include])
env.Alias("install_include", install_include)





