# For c-shell users: in you .cshrc set the following
# 
# on motown:
# setenv LOCAL_ROOT /d1/local
# setenv LOCAL_INC_DIR ${LOCAL_ROOT}/include
# setenv LOCAL_LIB_DIR ${LOCAL_ROOT}/lib
# setenv LOCAL_BIN_DIR ${LOCAL_ROOT}/bin
#
# setenv RAL_INC_DIR /usr/include
# setenv RAL_LIB_DIR /usr/lib
# setenv RAL_CCFLAGS "-Wall -g -O -static"

import os

env = Environment(CPPPATH=[os.environ["NETCDF_INC_DIR"], os.environ["HDF_INC_DIR"],os.environ["LOCAL_INC_DIR"]], CCFLAGS=os.environ["RAL_CCFLAGS"], LIBPATH=[os.environ["NETCDF_LIB_DIR"], os.environ["HDF_LIB_DIR"], os.environ["ZLIB_LIB_DIR"], os.environ["SZIP_LIB_DIR"],os.environ["LOCAL_LIB_DIR"]])

env["INSTALLPATH"] = os.environ["LOCAL_BIN_DIR"]

env.Append(LINKFLAGS = Split('-z origin'))
env.Append( RPATH = env.Literal(os.path.join('\\$$ORIGIN', os.pardir, 'lib')))

env.Append(CPPDEFINES=['JSON_SPIRIT_VALUE_ENABLED'])

probe_to_json = env.Program(
    "probe_to_json", [
    "main.cc",
    "arguments.cc",
    "convert.cc",
    "process.cc",
    "config_reader.cc",
    "json_writer.cc"
                                   ],LIBS=[
                                           "json_spirit",
                                           "libconfig++",
                                           "log",
                                           "rwx",
                                           "netcdf_c++4",
                                           "netcdf_c++",
                                           "netcdf",
                                           "hdf5_hl",
                                           "hdf5",
                                           "sz",
                                           "z",
                                           "udunits2",
                                           "expat",
                                           "vdt4"
                                           ]
    )

env.Install(os.environ["LOCAL_BIN_DIR"], "probe_to_json")
env.Alias("install", [os.environ["LOCAL_BIN_DIR"]])
