
import os
env = Environment(CPPPATH=[os.environ["LOCAL_INC_DIR"], os.environ["RAL_INC_DIR"], "include"], LIBPATH=[os.environ["LOCAL_LIB_DIR"], os.environ["RAL_LIB_DIR"]], CCFLAGS=os.environ["RAL_CCFLAGS"])
    
env.Library("Proj4Wrap", [
    "Proj4Wrap/Proj4Wrap.cc"
  ]
            )

env.Install(env["LIBPATH"], "libProj4Wrap.a")

install_include = "%s/Proj4Wrap" % os.environ["LOCAL_INC_DIR"]

env.Install(install_include, ["include/Proj4Wrap/Proj4Wrap.hh"])


env.Alias("install", [os.environ["LOCAL_LIB_DIR"], install_include])
env.Alias("install_include", install_include)
