// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* 
// ** Copyright UCAR (c) 1992 - 2014 
// ** University Corporation for Atmospheric Research(UCAR) 
// ** National Center for Atmospheric Research(NCAR) 
// ** Research Applications Laboratory(RAL) 
// ** P.O.Box 3000, Boulder, Colorado, 80307-3000, USA 
// ** See LICENCE.TXT if applicable for licence details 
// ** 2014/10/20 13:00:00 
// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* 

#include <string.h>
#include "vdt_probe_message_qc_file_writer.hh"

const char* vdt_probe_message_qc_file_writer::VEHICLE_ID_LEN = "vehicle_id_len";
const char* vdt_probe_message_qc_file_writer::OBS_TIME = "obs_time";
const char* vdt_probe_message_qc_file_writer::REC_TIME = "rec_time";
const char* vdt_probe_message_qc_file_writer::VEHICLE_ID = "vehicle_id";
const char* vdt_probe_message_qc_file_writer::LATITUDE = "latitude";
const char* vdt_probe_message_qc_file_writer::LATITUDE_DFT_PASSED = "latitude_dft_passed";
const char* vdt_probe_message_qc_file_writer::LONGITUDE = "longitude";
const char* vdt_probe_message_qc_file_writer::LONGITUDE_DFT_PASSED = "longitude_dft_passed";
const char* vdt_probe_message_qc_file_writer::ELEVATION = "elevation";
const char* vdt_probe_message_qc_file_writer::ROAD_SEGMENT_ID = "road_segment_id";
const char* vdt_probe_message_qc_file_writer::SPEED = "speed";
const char* vdt_probe_message_qc_file_writer::SPEED_RANGE_QC_PASSED = "speed_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP = "air_temp";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP_RANGE_QC_PASSED = "air_temp_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP_SDT_PASSED = "air_temp_sdt_passed";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP_NST_PASSED = "air_temp_nst_passed";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP_MAT_PASSED = "air_temp_mat_passed";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP_CRT_PASSED = "air_temp_crt_passed";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP_CAT_PASSED = "air_temp_cat_passed";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP_CAT_CONFIDENCE = "air_temp_cat_confidence";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP_NVT_PASSED = "air_temp_nvt_passed";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP_PERSIST_PASSED = "air_temp_persist_passed";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP_SPATIAL_BARNES_PASSED = "air_temp_spatial_barnes_passed";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP_SPATIAL_IQR_PASSED = "air_temp_spatial_iqr_passed";
const char* vdt_probe_message_qc_file_writer::AIR_TEMP_STEP_PASSED = "air_temp_step_passed";
const char* vdt_probe_message_qc_file_writer::NSS_AIR_TEMP_MEAN = "nss_air_temp_mean";
const char* vdt_probe_message_qc_file_writer::MODEL_AIR_TEMP = "model_air_temp";
const char* vdt_probe_message_qc_file_writer::MODEL_DEWPOINT = "model_dewpoint";
const char* vdt_probe_message_qc_file_writer::BAR_PRESSURE = "bar_pressure";
const char* vdt_probe_message_qc_file_writer::BAR_PRESS_RANGE_QC_PASSED = "bar_press_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::BAR_PRESS_SDT_PASSED = "bar_press_sdt_passed";
const char* vdt_probe_message_qc_file_writer::BAR_PRESS_NST_PASSED = "bar_press_nst_passed";
const char* vdt_probe_message_qc_file_writer::BAR_PRESS_MAT_PASSED = "bar_press_mat_passed";
const char* vdt_probe_message_qc_file_writer::BAR_PRESS_CRT_PASSED = "bar_press_crt_passed";
const char* vdt_probe_message_qc_file_writer::BAR_PRESS_CAT_PASSED = "bar_press_cat_passed";
const char* vdt_probe_message_qc_file_writer::BAR_PRESS_CAT_CONFIDENCE = "bar_press_cat_confidence";
const char* vdt_probe_message_qc_file_writer::BAR_PRESS_NVT_PASSED = "bar_press_nvt_passed";
const char* vdt_probe_message_qc_file_writer::BAR_PRESS_PERSIST_PASSED = "bar_press_persist_passed";
const char* vdt_probe_message_qc_file_writer::BAR_PRESS_SPATIAL_BARNES_PASSED = "bar_press_spatial_barnes_passed";
const char* vdt_probe_message_qc_file_writer::BAR_PRESS_SPATIAL_IQR_PASSED = "bar_press_spatial_iqr_passed";
const char* vdt_probe_message_qc_file_writer::BAR_PRESS_STEP_PASSED = "bar_press_step_passed";
const char* vdt_probe_message_qc_file_writer::NSS_BAR_PRESS_MEAN = "nss_bar_press_mean";
const char* vdt_probe_message_qc_file_writer::MODEL_BAR_PRESS = "model_bar_press";
const char* vdt_probe_message_qc_file_writer::RADAR_REF = "radar_ref";
const char* vdt_probe_message_qc_file_writer::RADAR_PRECIP_FLAG = "radar_precip_flag";
const char* vdt_probe_message_qc_file_writer::RADAR_PRECIP_TYPE = "radar_precip_type";
const char* vdt_probe_message_qc_file_writer::CLOUD_MASK = "cloud_mask";
const char* vdt_probe_message_qc_file_writer::NSS_DEW_TEMP_MEAN = "nss_dew_temp_mean";
const char* vdt_probe_message_qc_file_writer::NSS_WIND_DIR_MEAN = "nss_wind_dir_mean";
const char* vdt_probe_message_qc_file_writer::NSS_WIND_SPEED_MEAN = "nss_wind_speed_mean";
const char* vdt_probe_message_qc_file_writer::NSS_HOURLY_PRECIP_MEAN = "nss_hourly_precip_mean";
const char* vdt_probe_message_qc_file_writer::NSS_PREVAIL_VIS_MEAN = "nss_prevail_vis_mean";
const char* vdt_probe_message_qc_file_writer::BRAKE_STATUS = "brake_status";
const char* vdt_probe_message_qc_file_writer::BRAKE_STATUS_RANGE_QC_PASSED = "brake_status_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::BRAKE_BOOST = "brake_boost";
const char* vdt_probe_message_qc_file_writer::BRAKE_BOOST_RANGE_QC_PASSED = "brake_boost_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::WIPER_STATUS = "wiper_status";
const char* vdt_probe_message_qc_file_writer::WIPER_STATUS_RANGE_QC_PASSED = "wiper_status_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::TRAC = "trac";
const char* vdt_probe_message_qc_file_writer::TRAC_RANGE_QC_PASSED = "trac_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::STAB = "stab";
const char* vdt_probe_message_qc_file_writer::STAB_RANGE_QC_PASSED = "stab_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::ABS = "abs";
const char* vdt_probe_message_qc_file_writer::ABS_RANGE_QC_PASSED = "abs_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::LIGHTS = "lights";
const char* vdt_probe_message_qc_file_writer::LIGHTS_RANGE_QC_PASSED = "lights_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::HEADING = "heading";
const char* vdt_probe_message_qc_file_writer::HEADING_RANGE_QC_PASSED = "heading_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::YAW_RATE = "yaw_rate";
const char* vdt_probe_message_qc_file_writer::YAW_RATE_RANGE_QC_PASSED = "yaw_rate_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::LON_ACCEL = "hoz_accel_long";
const char* vdt_probe_message_qc_file_writer::LON_ACCEL_RANGE_QC_PASSED = "hoz_accel_long_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::LAT_ACCEL = "hoz_accel_lat";
const char* vdt_probe_message_qc_file_writer::LAT_ACCEL_RANGE_QC_PASSED = "hoz_accel_lat_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::STEERING_ANGLE = "steering_angle";
const char* vdt_probe_message_qc_file_writer::STEERING_ANGLE_RANGE_QC_PASSED = "steering_angle_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::STEERING_RATE = "steering_rate";
const char* vdt_probe_message_qc_file_writer::STEERING_RATE_RANGE_QC_PASSED = "steering_rate_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP = "air_temp2";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP_RANGE_QC_PASSED = "air_temp2_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP_SDT_PASSED = "air_temp2_sdt_passed";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP_NST_PASSED = "air_temp2_nst_passed";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP_MAT_PASSED = "air_temp2_mat_passed";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP_CRT_PASSED = "air_temp2_crt_passed";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP_CAT_PASSED = "air_temp2_cat_passed";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP_CAT_CONFIDENCE = "air_temp2_cat_confidence";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP_NVT_PASSED = "air_temp2_nvt_passed";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP_PERSIST_PASSED = "air_temp2_persist_passed";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP_SPATIAL_BARNES_PASSED = "air_temp2_spatial_barnes_passed";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP_SPATIAL_IQR_PASSED = "air_temp2_spatial_iqr_passed";
const char* vdt_probe_message_qc_file_writer::EXTERNAL_AIR_TEMP_STEP_PASSED = "air_temp2_step_passed";
const char* vdt_probe_message_qc_file_writer::SURFACE_TEMP = "surface_temp";
const char* vdt_probe_message_qc_file_writer::SURFACE_TEMP_RANGE_QC_PASSED = "surface_temp_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::SURFACE_TEMP_CRT_PASSED = "surface_temp_crt_passed";
const char* vdt_probe_message_qc_file_writer::SURFACE_TEMP_CAT_PASSED = "surface_temp_cat_passed";
const char* vdt_probe_message_qc_file_writer::SURFACE_TEMP_CAT_CONFIDENCE = "surface_temp_cat_confidence";
const char* vdt_probe_message_qc_file_writer::SURFACE_TEMP_NVT_PASSED = "surface_temp_nvt_passed";
const char* vdt_probe_message_qc_file_writer::SURFACE_TEMP_PERSIST_PASSED = "surface_temp_persist_passed";
const char* vdt_probe_message_qc_file_writer::SURFACE_TEMP_SDT_PASSED = "surface_temp_sdt_passed";
const char* vdt_probe_message_qc_file_writer::SURFACE_TEMP_SPATIAL_BARNES_PASSED = "surface_temp_spatial_barnes_passed";
const char* vdt_probe_message_qc_file_writer::SURFACE_TEMP_SPATIAL_IQR_PASSED = "surface_temp_spatial_iqr_passed";
const char* vdt_probe_message_qc_file_writer::SURFACE_TEMP_STEP_PASSED = "surface_temp_step_passed";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP = "dew_temp";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP_CAT_PASSED = "dew_temp_cat_passed";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP_CAT_CONFIDENCE = "dew_temp_cat_confidence";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP_CRT_PASSED = "dew_temp_crt_passed";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP_MAT_PASSED = "dew_temp_mat_passed";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP_NST_PASSED = "dew_temp_nst_passed";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP_NVT_PASSED = "dew_temp_nvt_passed";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP_PERSIST_PASSED = "dew_temp_persist_passed";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP_RANGE_QC_PASSED = "dew_temp_range_qc_passed";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP_SDT_PASSED = "dew_temp_sdt_passed";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP_SPATIAL_BARNES_PASSED = "dew_temp_spatial_barnes_passed";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP_SPATIAL_IQR_PASSED = "dew_temp_spatial_iqr_passed";
const char* vdt_probe_message_qc_file_writer::DEW_TEMP_STEP_PASSED = "dew_temp_step_passed";


vdt_probe_message_qc_file_writer::~vdt_probe_message_qc_file_writer()
{
}

int vdt_probe_message_qc_file_writer::write_probe_messages(const vector<vdt_probe_message_qc>& msgs)
{
  int n = msgs.size();
  int vehicle_id_len = nc->get_dim(VEHICLE_ID_LEN)->size();
  NcVar* obs_time_var = nc->get_var(OBS_TIME);
  NcVar* rec_time_var = nc->get_var(REC_TIME);
  NcVar* vehicle_id_var = nc->get_var(VEHICLE_ID);
  NcVar* lat_var = nc->get_var(LATITUDE);
  NcVar* latitude_dft_passed_var = nc->get_var(LATITUDE_DFT_PASSED);
  NcVar* lon_var = nc->get_var(LONGITUDE);
  NcVar* longitude_dft_passed_var = nc->get_var(LONGITUDE_DFT_PASSED);
  NcVar* elev_var = nc->get_var(ELEVATION);
  NcVar* road_segment_id_var = nc->get_var(ROAD_SEGMENT_ID);
  NcVar* speed_var = nc->get_var(SPEED);
  NcVar* speed_range_qc_passed_var = nc->get_var(SPEED_RANGE_QC_PASSED);
  NcVar* air_temp_var = nc->get_var(AIR_TEMP);
  NcVar* air_temp_range_qc_passed_var = nc->get_var(AIR_TEMP_RANGE_QC_PASSED);
  NcVar* air_temp_sdt_passed_var = nc->get_var(AIR_TEMP_SDT_PASSED);
  NcVar* air_temp_nst_passed_var = nc->get_var(AIR_TEMP_NST_PASSED);
  NcVar* air_temp_mat_passed_var = nc->get_var(AIR_TEMP_MAT_PASSED);
  NcVar* air_temp_crt_passed_var = nc->get_var(AIR_TEMP_CRT_PASSED);
  NcVar* air_temp_cat_passed_var = nc->get_var(AIR_TEMP_CAT_PASSED);
  NcVar* air_temp_cat_confidence_var = nc->get_var(AIR_TEMP_CAT_CONFIDENCE);
  NcVar* air_temp_nvt_passed_var = nc->get_var(AIR_TEMP_NVT_PASSED);
  NcVar* air_temp_persist_passed_var = nc->get_var(AIR_TEMP_PERSIST_PASSED);
  NcVar* air_temp_spatial_barnes_qc_passed_var = nc->get_var(AIR_TEMP_SPATIAL_BARNES_PASSED);
  NcVar* air_temp_spatial_iqr_qc_passed_var = nc->get_var(AIR_TEMP_SPATIAL_IQR_PASSED);
  NcVar* air_temp_step_passed_var = nc->get_var(AIR_TEMP_STEP_PASSED);
  NcVar* nss_air_temp_mean_var = nc->get_var(NSS_AIR_TEMP_MEAN);
  NcVar* model_air_temp_var = nc->get_var(MODEL_AIR_TEMP);
  NcVar* bar_press_var = nc->get_var(BAR_PRESSURE);
  NcVar* bar_press_range_qc_passed_var = nc->get_var(BAR_PRESS_RANGE_QC_PASSED);
  NcVar* bar_press_sdt_passed_var = nc->get_var(BAR_PRESS_SDT_PASSED);
  NcVar* bar_press_nst_passed_var = nc->get_var(BAR_PRESS_NST_PASSED);
  NcVar* bar_press_mat_passed_var = nc->get_var(BAR_PRESS_MAT_PASSED);
  NcVar* bar_press_crt_passed_var = nc->get_var(BAR_PRESS_CRT_PASSED);
  NcVar* bar_press_cat_passed_var = nc->get_var(BAR_PRESS_CAT_PASSED);
  NcVar* bar_press_cat_confidence_var = nc->get_var(BAR_PRESS_CAT_CONFIDENCE);
  NcVar* bar_press_nvt_passed_var = nc->get_var(BAR_PRESS_NVT_PASSED);
  NcVar* bar_press_persist_passed_var = nc->get_var(BAR_PRESS_PERSIST_PASSED);
  NcVar* bar_press_spatial_barnes_qc_passed_var = nc->get_var(BAR_PRESS_SPATIAL_BARNES_PASSED);
  NcVar* bar_press_spatial_iqr_qc_passed_var = nc->get_var(BAR_PRESS_SPATIAL_IQR_PASSED);
  NcVar* bar_press_step_passed_var = nc->get_var(BAR_PRESS_STEP_PASSED);
  NcVar* nss_bar_press_mean_var = nc->get_var(NSS_BAR_PRESS_MEAN);
  NcVar* model_bar_press_var = nc->get_var(MODEL_BAR_PRESS);
  NcVar* radar_ref_var = nc->get_var(RADAR_REF);
  NcVar* radar_precip_flag_var = nc->get_var(RADAR_PRECIP_FLAG);
  NcVar* radar_precip_type_var = nc->get_var(RADAR_PRECIP_TYPE);
  NcVar* cloud_mask_var = nc->get_var(CLOUD_MASK);
  NcVar* nss_dew_temp_mean_var = nc->get_var(NSS_DEW_TEMP_MEAN);
  NcVar* nss_wind_dir_mean_var = nc->get_var(NSS_WIND_DIR_MEAN);
  NcVar* nss_wind_speed_mean_var = nc->get_var(NSS_WIND_SPEED_MEAN);
  NcVar* nss_hourly_precip_mean_var = nc->get_var(NSS_HOURLY_PRECIP_MEAN);
  NcVar* nss_prevail_vis_mean_var = nc->get_var(NSS_PREVAIL_VIS_MEAN);
  NcVar* brake_status_var = nc->get_var(BRAKE_STATUS);
  NcVar* brake_status_range_qc_passed_var = nc->get_var(BRAKE_STATUS_RANGE_QC_PASSED);
  NcVar* brake_boost_var = nc->get_var(BRAKE_BOOST);
  NcVar* brake_boost_range_qc_passed_var = nc->get_var(BRAKE_BOOST_RANGE_QC_PASSED);
  NcVar* wiper_status_var = nc->get_var(WIPER_STATUS);
  NcVar* wiper_status_range_qc_passed_var = nc->get_var(WIPER_STATUS_RANGE_QC_PASSED);
  NcVar* trac_var = nc->get_var(TRAC);
  NcVar* trac_range_qc_passed_var = nc->get_var(TRAC_RANGE_QC_PASSED);
  NcVar* stab_var = nc->get_var(STAB);
  NcVar* stab_range_qc_passed_var = nc->get_var(STAB_RANGE_QC_PASSED);
  NcVar* abs_var = nc->get_var(ABS);
  NcVar* abs_range_qc_passed_var = nc->get_var(ABS_RANGE_QC_PASSED);
  NcVar* lights_var = nc->get_var(LIGHTS);
  NcVar* lights_range_qc_passed_var = nc->get_var(LIGHTS_RANGE_QC_PASSED);
  NcVar* heading_var = nc->get_var(HEADING);
  NcVar* heading_range_qc_passed_var = nc->get_var(HEADING_RANGE_QC_PASSED);
  NcVar* yaw_rate_var = nc->get_var(YAW_RATE);
  NcVar* yaw_rate_range_qc_passed_var = nc->get_var(YAW_RATE_RANGE_QC_PASSED);
  NcVar* lon_accel_var = nc->get_var(LON_ACCEL);
  NcVar* lon_accel_range_qc_passed_var = nc->get_var(LON_ACCEL_RANGE_QC_PASSED);
  NcVar* lat_accel_var = nc->get_var(LAT_ACCEL);
  NcVar* lat_accel_range_qc_passed_var = nc->get_var(LAT_ACCEL_RANGE_QC_PASSED);
  NcVar* steer_angle_var = nc->get_var(STEERING_ANGLE);
  NcVar* steer_angle_range_qc_passed_var = nc->get_var(STEERING_ANGLE_RANGE_QC_PASSED);
  NcVar* steer_rate_var = nc->get_var(STEERING_RATE);
  NcVar* steer_rate_range_qc_passed_var = nc->get_var(STEERING_RATE_RANGE_QC_PASSED);
  NcVar* ext_air_temp_var = nc->get_var(EXTERNAL_AIR_TEMP);
  NcVar* ext_air_temp_range_qc_passed_var = nc->get_var(EXTERNAL_AIR_TEMP_RANGE_QC_PASSED);
  NcVar* ext_air_temp_sdt_passed_var = nc->get_var(EXTERNAL_AIR_TEMP_SDT_PASSED);
  NcVar* ext_air_temp_nst_passed_var = nc->get_var(EXTERNAL_AIR_TEMP_NST_PASSED);
  NcVar* ext_air_temp_mat_passed_var = nc->get_var(EXTERNAL_AIR_TEMP_MAT_PASSED);
  NcVar* ext_air_temp_crt_passed_var = nc->get_var(EXTERNAL_AIR_TEMP_CRT_PASSED);
  NcVar* ext_air_temp_cat_passed_var = nc->get_var(EXTERNAL_AIR_TEMP_CAT_PASSED);
  NcVar* ext_air_temp_cat_confidence_var = nc->get_var(EXTERNAL_AIR_TEMP_CAT_CONFIDENCE);
  NcVar* ext_air_temp_nvt_passed_var = nc->get_var(EXTERNAL_AIR_TEMP_NVT_PASSED);
  NcVar* ext_air_temp_persist_passed_var = nc->get_var(EXTERNAL_AIR_TEMP_PERSIST_PASSED);
  NcVar* ext_air_temp_spatial_barnes_qc_passed_var = nc->get_var(EXTERNAL_AIR_TEMP_SPATIAL_BARNES_PASSED);
  NcVar* ext_air_temp_spatial_iqr_qc_passed_var = nc->get_var(EXTERNAL_AIR_TEMP_SPATIAL_IQR_PASSED);
  NcVar* ext_air_temp_step_passed_var = nc->get_var(EXTERNAL_AIR_TEMP_STEP_PASSED);
  NcVar* surface_temp_var = nc->get_var(SURFACE_TEMP);
  NcVar* surface_temp_range_qc_passed_var = nc->get_var(SURFACE_TEMP_RANGE_QC_PASSED);
  NcVar* surface_temp_crt_passed_var = nc->get_var(SURFACE_TEMP_CRT_PASSED);
  NcVar* surface_temp_cat_passed_var = nc->get_var(SURFACE_TEMP_CAT_PASSED);
  NcVar* surface_temp_cat_confidence_var = nc->get_var(SURFACE_TEMP_CAT_CONFIDENCE);
  NcVar* surface_temp_sdt_passed_var = nc->get_var(SURFACE_TEMP_SDT_PASSED);
  NcVar* surface_temp_nvt_passed_var = nc->get_var(SURFACE_TEMP_NVT_PASSED);
  NcVar* surface_temp_persist_passed_var = nc->get_var(SURFACE_TEMP_PERSIST_PASSED);
  NcVar* surface_temp_spatial_barnes_qc_passed_var = nc->get_var(SURFACE_TEMP_SPATIAL_BARNES_PASSED);
  NcVar* surface_temp_spatial_iqr_qc_passed_var = nc->get_var(SURFACE_TEMP_SPATIAL_IQR_PASSED);
  NcVar* surface_temp_step_passed_var = nc->get_var(SURFACE_TEMP_STEP_PASSED);
  NcVar* dew_temp_var = nc->get_var(DEW_TEMP);
  NcVar* dew_temp_cat_passed_var = nc->get_var(DEW_TEMP_CAT_PASSED);
  NcVar* dew_temp_cat_confidence_var = nc->get_var(DEW_TEMP_CAT_CONFIDENCE);
  NcVar* dew_temp_crt_passed_var = nc->get_var(DEW_TEMP_CRT_PASSED);
  NcVar* dew_temp_mat_passed_var = nc->get_var(DEW_TEMP_MAT_PASSED);
  NcVar* dew_temp_nst_passed_var = nc->get_var(DEW_TEMP_NST_PASSED);
  NcVar* dew_temp_nvt_passed_var = nc->get_var(DEW_TEMP_NVT_PASSED);
  NcVar* dew_temp_persist_passed_var = nc->get_var(DEW_TEMP_PERSIST_PASSED);
  NcVar* dew_temp_range_qc_passed_var = nc->get_var(DEW_TEMP_RANGE_QC_PASSED);
  NcVar* dew_temp_sdt_passed_var = nc->get_var(DEW_TEMP_SDT_PASSED);
  NcVar* dew_temp_spatial_barnes_qc_passed_var = nc->get_var(DEW_TEMP_SPATIAL_BARNES_PASSED);
  NcVar* dew_temp_spatial_iqr_qc_passed_var = nc->get_var(DEW_TEMP_SPATIAL_IQR_PASSED);
  NcVar* dew_temp_step_passed_var = nc->get_var(DEW_TEMP_STEP_PASSED);
  NcVar* model_dewpoint_var = nc->get_var(MODEL_DEWPOINT);

  char* vehicle_id = new char[vehicle_id_len];
  for (int i = 0; i < n; i++)
    {
      vdt_probe_message_qc msg = msgs[i];
      double obs_time = msg.get_obs_time();
      double rec_time = msg.get_rec_time();
      strncpy(vehicle_id, msg.get_vehicle_id().c_str(), vehicle_id_len);
      float elev = msg.get_elevation();
      double lat = msg.get_latitude();
      double latitude_dft_passed = msg.get_latitude_dft_passed();
      double lon = msg.get_longitude();
      double longitude_dft_passed = msg.get_longitude_dft_passed();
      int road_segment_id = msg.get_road_segment_id();
      float speed = msg.get_speed();
      short brake_status = msg.get_brake_status();
      float yaw = msg.get_yaw();
      float lon_accel = msg.get_hoz_accel_long();
      float lat_accel = msg.get_hoz_accel_lat();
      float steer_angle = msg.get_steering_angle();
      short steer_rate = msg.get_steering_rate();
      float heading = msg.get_heading();
      short wipers = msg.get_wipers_front_status();
      short air_temp = msg.get_air_temp();
      float ext_air_temp = msg.get_air_temp2();
      short bar_press = msg.get_bar_press();
      short trac = msg.get_trac();
      short stab = msg.get_stab();
      short lights = msg.get_lights();
      short abs = msg.get_abs();
      short brake_boost = msg.get_brake_boost();
      float nss_air_temp_mean = msg.get_nss_air_temp_mean();
      float nss_bar_press_mean = msg.get_nss_bar_press_mean();
      float model_air_temp = msg.get_model_air_temp();
      float model_dewpoint = msg.get_model_dewpoint();
      float model_bar_press = msg.get_model_bar_press();
      float ref = msg.get_radar_ref();
      short precip_flag = msg.get_radar_precip_flag();
      short precip_type = msg.get_radar_precip_type();
      short cloud_mask = (short)msg.get_cloud_mask();
      float nss_dew_temp_mean = msg.get_nss_dew_temp_mean();
      float nss_wind_dir_mean = msg.get_nss_wind_dir_mean();
      float nss_wind_speed_mean = msg.get_nss_wind_speed_mean();
      float nss_hourly_precip_mean = msg.get_nss_hourly_precip_mean();
      float nss_prevail_vis_mean = msg.get_nss_prevail_vis_mean();
      short heading_passed = (int)msg.get_heading_range_qc_passed();
      short speed_passed = (int)msg.get_speed_range_qc_passed();
      short brake_status_passed = (int)msg.get_brake_status_range_qc_passed();
      short brake_boost_passed = (int)msg.get_brake_boost_range_qc_passed();
      short abs_passed = (int)msg.get_abs_range_qc_passed();
      short stab_passed = (int)msg.get_stab_range_qc_passed();
      short trac_passed = (int)msg.get_trac_range_qc_passed();
      short lights_passed = (int)msg.get_lights_range_qc_passed();
      short yaw_passed = (int)msg.get_yaw_range_qc_passed();
      short lon_accel_passed = (int)msg.get_hoz_accel_long_range_qc_passed();
      short lat_accel_passed = (int)msg.get_hoz_accel_lat_range_qc_passed();
      short steer_angle_passed = (int)msg.get_steering_angle_range_qc_passed();
      short steer_rate_passed = (int)msg.get_steering_rate_range_qc_passed();
      short wipers_passed = (int)msg.get_wipers_front_status_range_qc_passed();
      short air_temp_range_qc_passed = (int)msg.get_air_temp_range_qc_passed();
      short air_temp_sdt_passed = (int)msg.get_air_temp_sdt_passed();
      short air_temp_nst_passed = (int)msg.get_air_temp_nst_passed();
      short air_temp_mat_passed = (int)msg.get_air_temp_mat_passed();
      short air_temp_crt_passed = (int)msg.get_air_temp_crt_passed();
      short air_temp_cat_passed = (int)msg.get_air_temp_cat_passed();
      float air_temp_cat_confidence = (float)msg.get_air_temp_cat_confidence();
      short air_temp_nvt_passed = (int)msg.get_air_temp_nvt_passed();
      short air_temp_persist_passed = (int)msg.get_air_temp_persist_passed();
      short air_temp_spatial_barnes_qc_passed = (int)msg.get_air_temp_spatial_barnes_qc_passed();
      short air_temp_spatial_iqr_qc_passed = (int)msg.get_air_temp_spatial_iqr_qc_passed();
      short air_temp_step_passed = (int)msg.get_air_temp_step_passed();
      short bar_press_range_qc_passed = (int)msg.get_bar_press_range_qc_passed();
      short bar_press_sdt_passed = (int)msg.get_bar_press_sdt_passed();
      short bar_press_nst_passed = (int)msg.get_bar_press_nst_passed();
      short bar_press_mat_passed = (int)msg.get_bar_press_mat_passed();
      short bar_press_crt_passed = (int)msg.get_bar_press_crt_passed();
      short bar_press_cat_passed = (int)msg.get_bar_press_cat_passed();
      float bar_press_cat_confidence = (float)msg.get_bar_press_cat_confidence();
      short bar_press_nvt_passed = (int)msg.get_bar_press_nvt_passed();
      short bar_press_persist_passed = (int)msg.get_bar_press_persist_passed();
      short bar_press_spatial_barnes_qc_passed = (int)msg.get_bar_press_spatial_barnes_qc_passed();
      short bar_press_spatial_iqr_qc_passed = (int)msg.get_bar_press_spatial_iqr_qc_passed();
      short bar_press_step_passed = (int)msg.get_bar_press_step_passed();
      short ext_air_temp_range_qc_passed = (int)msg.get_air_temp2_range_qc_passed();
      short ext_air_temp_sdt_passed = (int)msg.get_air_temp2_sdt_passed();
      short ext_air_temp_nst_passed = (int)msg.get_air_temp2_nst_passed();
      short ext_air_temp_mat_passed = (int)msg.get_air_temp2_mat_passed();
      short ext_air_temp_crt_passed = (int)msg.get_air_temp2_crt_passed();
      short ext_air_temp_cat_passed = (int)msg.get_air_temp2_cat_passed();
      float ext_air_temp_cat_confidence = (float)msg.get_air_temp2_cat_confidence();
      short ext_air_temp_nvt_passed = (int)msg.get_air_temp2_nvt_passed();
      short ext_air_temp_persist_passed = (int)msg.get_air_temp2_persist_passed();
      short ext_air_temp_spatial_barnes_qc_passed = (int)msg.get_air_temp2_spatial_barnes_qc_passed();
      short ext_air_temp_spatial_iqr_qc_passed = (int)msg.get_air_temp2_spatial_iqr_qc_passed();
      short ext_air_temp_step_passed = (int)msg.get_air_temp2_step_passed();
      float surface_temp = msg.get_surface_temp();
      short surface_temp_range_qc_passed = (int)msg.get_surface_temp_range_qc_passed();
      short surface_temp_crt_passed = (int)msg.get_surface_temp_crt_passed();
      short surface_temp_cat_passed = (int)msg.get_surface_temp_cat_passed();
      float surface_temp_cat_confidence = (float)msg.get_surface_temp_cat_confidence();
      short surface_temp_nvt_passed = (int)msg.get_surface_temp_nvt_passed();
      short surface_temp_persist_passed = (int)msg.get_surface_temp_persist_passed();
      short surface_temp_sdt_passed = (int)msg.get_surface_temp_sdt_passed();
      short surface_temp_spatial_barnes_qc_passed = (int)msg.get_surface_temp_spatial_barnes_qc_passed();
      short surface_temp_spatial_iqr_qc_passed = (int)msg.get_surface_temp_spatial_iqr_qc_passed();
      short surface_temp_step_passed = (int)msg.get_surface_temp_step_passed();
      float dew_temp = msg.get_dew_temp();
      short dew_temp_cat_passed = (int)msg.get_dew_temp_cat_passed();
      float dew_temp_cat_confidence = (float)msg.get_dew_temp_cat_confidence();
      short dew_temp_crt_passed = (int)msg.get_dew_temp_crt_passed();
      short dew_temp_mat_passed = (int)msg.get_dew_temp_mat_passed();
      short dew_temp_nst_passed = (int)msg.get_dew_temp_nst_passed();
      short dew_temp_nvt_passed = (int)msg.get_dew_temp_nvt_passed();
      short dew_temp_persist_passed = (int)msg.get_dew_temp_persist_passed();
      short dew_temp_range_qc_passed = (int)msg.get_dew_temp_range_qc_passed();
      short dew_temp_sdt_passed = (int)msg.get_dew_temp_sdt_passed();
      short dew_temp_spatial_barnes_qc_passed = (int)msg.get_dew_temp_spatial_barnes_qc_passed();
      short dew_temp_spatial_iqr_qc_passed = (int)msg.get_dew_temp_spatial_iqr_qc_passed();
      short dew_temp_step_passed = (int)msg.get_dew_temp_step_passed();

      obs_time_var->set_cur(i);
      rec_time_var->set_cur(i);
      vehicle_id_var->set_cur(i);
      lat_var->set_cur(i);
      latitude_dft_passed_var->set_cur(i);
      lon_var->set_cur(i);
      longitude_dft_passed_var->set_cur(i);
      elev_var->set_cur(i);
      road_segment_id_var->set_cur(i);
      speed_var->set_cur(i);
      speed_range_qc_passed_var->set_cur(i);
      air_temp_var->set_cur(i);
      air_temp_range_qc_passed_var->set_cur(i);
      air_temp_crt_passed_var->set_cur(i);
      air_temp_cat_passed_var->set_cur(i);
      air_temp_cat_confidence_var->set_cur(i);
      air_temp_nvt_passed_var->set_cur(i);
      air_temp_sdt_passed_var->set_cur(i);
      air_temp_nst_passed_var->set_cur(i);
      air_temp_mat_passed_var->set_cur(i);
      air_temp_persist_passed_var->set_cur(i);
      air_temp_spatial_barnes_qc_passed_var->set_cur(i);
      air_temp_spatial_iqr_qc_passed_var->set_cur(i);
      air_temp_step_passed_var->set_cur(i);
      nss_air_temp_mean_var->set_cur(i);
      model_air_temp_var->set_cur(i);
      bar_press_var->set_cur(i);
      bar_press_range_qc_passed_var->set_cur(i);
      bar_press_crt_passed_var->set_cur(i);
      bar_press_cat_passed_var->set_cur(i);
      bar_press_cat_confidence_var->set_cur(i);
      bar_press_nvt_passed_var->set_cur(i);
      bar_press_sdt_passed_var->set_cur(i);
      bar_press_nst_passed_var->set_cur(i);
      bar_press_mat_passed_var->set_cur(i);
      bar_press_persist_passed_var->set_cur(i);
      bar_press_spatial_barnes_qc_passed_var->set_cur(i);
      bar_press_spatial_iqr_qc_passed_var->set_cur(i);
      bar_press_step_passed_var->set_cur(i);
      nss_bar_press_mean_var->set_cur(i);
      model_bar_press_var->set_cur(i);
      radar_ref_var->set_cur(i);
      radar_precip_flag_var->set_cur(i);
      radar_precip_type_var->set_cur(i);
      cloud_mask_var->set_cur(i);
      nss_dew_temp_mean_var->set_cur(i);
      nss_wind_dir_mean_var->set_cur(i);
      nss_wind_speed_mean_var->set_cur(i);
      nss_hourly_precip_mean_var->set_cur(i);
      nss_prevail_vis_mean_var->set_cur(i);
      brake_status_var->set_cur(i);
      brake_status_range_qc_passed_var->set_cur(i);
      brake_boost_var->set_cur(i);
      brake_boost_range_qc_passed_var->set_cur(i);
      wiper_status_var->set_cur(i);
      wiper_status_range_qc_passed_var->set_cur(i);
      trac_var->set_cur(i);
      trac_range_qc_passed_var->set_cur(i);
      stab_var->set_cur(i);
      stab_range_qc_passed_var->set_cur(i);
      abs_var->set_cur(i);
      abs_range_qc_passed_var->set_cur(i);
      lights_var->set_cur(i);
      lights_range_qc_passed_var->set_cur(i);
      heading_var->set_cur(i);
      heading_range_qc_passed_var->set_cur(i);
      yaw_rate_var->set_cur(i);
      yaw_rate_range_qc_passed_var->set_cur(i);
      lon_accel_var->set_cur(i);
      lon_accel_range_qc_passed_var->set_cur(i);
      lat_accel_var->set_cur(i);
      lat_accel_range_qc_passed_var->set_cur(i);
      steer_angle_var->set_cur(i);
      steer_angle_range_qc_passed_var->set_cur(i);
      steer_rate_var->set_cur(i);
      steer_rate_range_qc_passed_var->set_cur(i);
      ext_air_temp_var->set_cur(i);
      ext_air_temp_range_qc_passed_var->set_cur(i);
      ext_air_temp_crt_passed_var->set_cur(i);
      ext_air_temp_cat_passed_var->set_cur(i);
      ext_air_temp_cat_confidence_var->set_cur(i);
      ext_air_temp_nvt_passed_var->set_cur(i);
      ext_air_temp_sdt_passed_var->set_cur(i);
      ext_air_temp_nst_passed_var->set_cur(i);
      ext_air_temp_mat_passed_var->set_cur(i);
      ext_air_temp_persist_passed_var->set_cur(i);
      ext_air_temp_spatial_barnes_qc_passed_var->set_cur(i);
      ext_air_temp_spatial_iqr_qc_passed_var->set_cur(i);
      ext_air_temp_step_passed_var->set_cur(i);
      surface_temp_var->set_cur(i);
      surface_temp_range_qc_passed_var->set_cur(i);
      surface_temp_crt_passed_var->set_cur(i);
      surface_temp_cat_passed_var->set_cur(i);
      surface_temp_cat_confidence_var->set_cur(i);
      surface_temp_nvt_passed_var->set_cur(i);
      surface_temp_persist_passed_var->set_cur(i);
      surface_temp_sdt_passed_var->set_cur(i);
      surface_temp_spatial_barnes_qc_passed_var->set_cur(i);
      surface_temp_spatial_iqr_qc_passed_var->set_cur(i);
      surface_temp_step_passed_var->set_cur(i);
      dew_temp_var->set_cur(i);
      dew_temp_cat_passed_var->set_cur(i);
      dew_temp_cat_confidence_var->set_cur(i);
      dew_temp_crt_passed_var->set_cur(i);
      dew_temp_mat_passed_var->set_cur(i);
      dew_temp_nst_passed_var->set_cur(i);
      dew_temp_nvt_passed_var->set_cur(i);
      dew_temp_persist_passed_var->set_cur(i);
      dew_temp_range_qc_passed_var->set_cur(i);
      dew_temp_sdt_passed_var->set_cur(i);
      dew_temp_spatial_barnes_qc_passed_var->set_cur(i);
      dew_temp_spatial_iqr_qc_passed_var->set_cur(i);
      dew_temp_step_passed_var->set_cur(i);
      model_dewpoint_var->set_cur(i);

      obs_time_var->put(&obs_time,1);
      rec_time_var->put(&rec_time,1);
      vehicle_id_var->put(vehicle_id,1,vehicle_id_len);
      lat_var->put(&lat,1);
      latitude_dft_passed_var->put(&latitude_dft_passed,1);
      lon_var->put(&lon,1);
      longitude_dft_passed_var->put(&longitude_dft_passed,1);
      elev_var->put(&elev,1);
      road_segment_id_var->put(&road_segment_id,1);
      speed_var->put(&speed,1);
      speed_range_qc_passed_var->put(&speed_passed,1);
      air_temp_var->put(&air_temp,1);
      air_temp_range_qc_passed_var->put(&air_temp_range_qc_passed,1);
      air_temp_crt_passed_var->put(&air_temp_crt_passed,1);
      air_temp_cat_passed_var->put(&air_temp_cat_passed,1);
      air_temp_cat_confidence_var->put(&air_temp_cat_confidence,1);
      air_temp_nvt_passed_var->put(&air_temp_nvt_passed,1);
      air_temp_sdt_passed_var->put(&air_temp_sdt_passed,1);
      air_temp_nst_passed_var->put(&air_temp_nst_passed,1);
      air_temp_mat_passed_var->put(&air_temp_mat_passed,1);
      air_temp_persist_passed_var->put(&air_temp_persist_passed,1);
      air_temp_spatial_barnes_qc_passed_var->put(&air_temp_spatial_barnes_qc_passed,1);
      air_temp_spatial_iqr_qc_passed_var->put(&air_temp_spatial_iqr_qc_passed,1);
      air_temp_step_passed_var->put(&air_temp_step_passed,1);
      nss_air_temp_mean_var->put(&nss_air_temp_mean,1);
      model_air_temp_var->put(&model_air_temp,1);
      bar_press_var->put(&bar_press,1);
      bar_press_range_qc_passed_var->put(&bar_press_range_qc_passed,1);
      bar_press_crt_passed_var->put(&bar_press_crt_passed,1);
      bar_press_cat_passed_var->put(&bar_press_cat_passed,1);
      bar_press_cat_confidence_var->put(&bar_press_cat_confidence,1);
      bar_press_nvt_passed_var->put(&bar_press_nvt_passed,1);
      bar_press_sdt_passed_var->put(&bar_press_sdt_passed,1);
      bar_press_nst_passed_var->put(&bar_press_nst_passed,1);
      bar_press_mat_passed_var->put(&bar_press_mat_passed,1);
      bar_press_persist_passed_var->put(&bar_press_persist_passed,1);
      bar_press_spatial_barnes_qc_passed_var->put(&bar_press_spatial_barnes_qc_passed,1);
      bar_press_spatial_iqr_qc_passed_var->put(&bar_press_spatial_iqr_qc_passed,1);
      bar_press_step_passed_var->put(&bar_press_step_passed,1);
      nss_bar_press_mean_var->put(&nss_bar_press_mean,1);
      model_bar_press_var->put(&model_bar_press,1);
      radar_ref_var->put(&ref,1);
      radar_precip_flag_var->put(&precip_flag,1);
      radar_precip_type_var->put(&precip_type,1);
      cloud_mask_var->put(&cloud_mask,1);
      nss_dew_temp_mean_var->put(&nss_dew_temp_mean,1);
      nss_wind_dir_mean_var->put(&nss_wind_dir_mean,1);
      nss_wind_speed_mean_var->put(&nss_wind_speed_mean,1);
      nss_hourly_precip_mean_var->put(&nss_hourly_precip_mean,1);
      nss_prevail_vis_mean_var->put(&nss_prevail_vis_mean,1);
      brake_status_var->put(&brake_status,1);
      brake_status_range_qc_passed_var->put(&brake_status_passed,1);
      brake_boost_var->put(&brake_boost,1);
      brake_boost_range_qc_passed_var->put(&brake_boost_passed,1);
      wiper_status_var->put(&wipers,1);
      wiper_status_range_qc_passed_var->put(&wipers_passed,1);
      trac_var->put(&trac,1);
      trac_range_qc_passed_var->put(&trac_passed,1);
      stab_var->put(&stab,1);
      stab_range_qc_passed_var->put(&stab_passed,1);
      abs_var->put(&abs,1);
      abs_range_qc_passed_var->put(&abs_passed,1);
      lights_var->put(&lights,1);
      lights_range_qc_passed_var->put(&lights_passed,1);
      heading_var->put(&heading,1);
      heading_range_qc_passed_var->put(&heading_passed,1);
      yaw_rate_var->put(&yaw,1);
      yaw_rate_range_qc_passed_var->put(&yaw_passed,1);
      lon_accel_var->put(&lon_accel,1);
      lon_accel_range_qc_passed_var->put(&lon_accel_passed,1);
      lat_accel_var->put(&lat_accel,1);
      lat_accel_range_qc_passed_var->put(&lat_accel_passed,1);
      steer_angle_var->put(&steer_angle,1);
      steer_angle_range_qc_passed_var->put(&steer_angle_passed,1);
      steer_rate_var->put(&steer_rate,1);
      steer_rate_range_qc_passed_var->put(&steer_rate_passed,1);
      ext_air_temp_var->put(&ext_air_temp,1);
      ext_air_temp_range_qc_passed_var->put(&ext_air_temp_range_qc_passed,1);
      ext_air_temp_crt_passed_var->put(&ext_air_temp_crt_passed,1);
      ext_air_temp_cat_passed_var->put(&ext_air_temp_cat_passed,1);
      ext_air_temp_cat_confidence_var->put(&ext_air_temp_cat_confidence,1);
      ext_air_temp_nvt_passed_var->put(&ext_air_temp_nvt_passed,1);
      ext_air_temp_sdt_passed_var->put(&ext_air_temp_sdt_passed,1);
      ext_air_temp_nst_passed_var->put(&ext_air_temp_nst_passed,1);
      ext_air_temp_mat_passed_var->put(&ext_air_temp_mat_passed,1);
      ext_air_temp_persist_passed_var->put(&ext_air_temp_persist_passed,1);
      ext_air_temp_spatial_barnes_qc_passed_var->put(&ext_air_temp_spatial_barnes_qc_passed,1);
      ext_air_temp_spatial_iqr_qc_passed_var->put(&ext_air_temp_spatial_iqr_qc_passed,1);
      ext_air_temp_step_passed_var->put(&ext_air_temp_step_passed,1);
      surface_temp_var->put(&surface_temp,1);
      surface_temp_range_qc_passed_var->put(&surface_temp_range_qc_passed,1);
      surface_temp_crt_passed_var->put(&surface_temp_crt_passed,1);
      surface_temp_cat_passed_var->put(&surface_temp_cat_passed,1);
      surface_temp_cat_confidence_var->put(&surface_temp_cat_confidence,1);
      surface_temp_nvt_passed_var->put(&surface_temp_nvt_passed,1);
      surface_temp_persist_passed_var->put(&surface_temp_persist_passed,1);
      surface_temp_sdt_passed_var->put(&surface_temp_sdt_passed,1);
      surface_temp_spatial_barnes_qc_passed_var->put(&surface_temp_spatial_barnes_qc_passed,1);
      surface_temp_spatial_iqr_qc_passed_var->put(&surface_temp_spatial_iqr_qc_passed,1);
      surface_temp_step_passed_var->put(&surface_temp_step_passed,1);
      dew_temp_var->put(&dew_temp,1);
      dew_temp_cat_passed_var->put(&dew_temp_cat_passed,1);
      dew_temp_cat_confidence_var->put(&dew_temp_cat_confidence,1);
      dew_temp_crt_passed_var->put(&dew_temp_crt_passed,1);
      dew_temp_mat_passed_var->put(&dew_temp_mat_passed,1);
      dew_temp_nst_passed_var->put(&dew_temp_nst_passed,1);
      dew_temp_nvt_passed_var->put(&dew_temp_nvt_passed,1);
      dew_temp_persist_passed_var->put(&dew_temp_persist_passed,1);
      dew_temp_range_qc_passed_var->put(&dew_temp_range_qc_passed,1);
      dew_temp_sdt_passed_var->put(&dew_temp_sdt_passed,1);
      dew_temp_spatial_barnes_qc_passed_var->put(&dew_temp_spatial_barnes_qc_passed,1);
      dew_temp_spatial_iqr_qc_passed_var->put(&dew_temp_spatial_iqr_qc_passed,1);
      dew_temp_step_passed_var->put(&dew_temp_step_passed,1);
      model_dewpoint_var->put(&model_dewpoint,1);

    }
  delete [] vehicle_id;
  return 0;
}
