

import os
env = Environment(CPPPATH= [os.environ["LOCAL_INC_DIR"], os.environ["RAL_INC_DIR"]], CCFLAGS=[os.environ["RAL_CCFLAGS"].split()], LIBPATH=[os.environ["LOCAL_LIB_DIR"], os.environ["RAL_LIB_DIR"]])
env["INSTALLPATH"] = os.environ["LOCAL_BIN_DIR"]
    
env.Program("rtma_example",
            ["rtma_example.cc"],
            LIBS=["proj", "m"]            
            )

env.Program("ruc2wrfgrid",
            ["ruc2wrfgrid.cc"],
            LIBS=["Proj4Wrap", "proj", "m"]            
            )

env.Program("lambertGrid",
            ["lambertGrid.cc", "LambertConfigReader.cc"],
            LIBS=["Proj4Wrap", "proj", "config++", "m"]
            )

env.Program("lambertGridLatLong",
            ["lambertGridLatLong.cc", "LambertConfigReaderLatLong.cc", "writeBinary.cc"],
            LIBS=["Proj4Wrap", "proj", "config++", "m"]
            )

env.Program("rtmall2xy",
            ["rtmall2xy.cc", "LambertConfigReaderLatLong.cc", "writeBinary.cc"],
            LIBS=["Proj4Wrap", "proj", "config++", "m"]
            )

env.Program("ructest",
            ["ructest.cc"],
            LIBS=["Proj4Wrap", "proj", "m"]            
            )

env.Program("ruc13ll2xy",
            ["ruc13ll2xy.cc"],
            LIBS=["Proj4Wrap", "proj", "m"]            
            )

env.Program("azimEqui",
            ["azimEqui.cc"],
            LIBS=["Proj4Wrap", "proj", "m"]            
            )

