
import os


env = Environment(CPPPATH=['.',
                           os.environ['NETCDF_INC_DIR'],
                           os.environ['HDF_INC_DIR'],
                           os.environ['ZLIB_INC_DIR'],
                           os.environ['LOCAL_INC_DIR']],
                  LIBPATH=[os.environ['NETCDF_LIB_DIR'],
                           os.environ['HDF5_LIB_DIR'],
                           os.environ['ZLIB_LIB_DIR'],
                           os.environ['LOCAL_LIB_DIR']],
                  CCFLAGS=[os.environ['CCFLAGS'],'-DUSE_JPEG2000 -DUSE_PNG'])

    
env.Library('grib2c', [
    'cmplxpack.c',
    'compack.c',
    'comunpack.c',
    'dec_jpeg2000.c',
    'dec_png.c',
    'drstemplates.c',
    'enc_jpeg2000.c',
    'enc_png.c',
    'g2_addfield.c',
    'g2_addgrid.c',
    'g2_addlocal.c',
    'g2_create.c',
    'g2_free.c',
    'g2_getfld.c',
    'g2_gribend.c',
    'g2_info.c',
    'g2_miss.c',
    'g2_unpack1.c',
    'g2_unpack2.c',
    'g2_unpack3.c',
    'g2_unpack4.c',
    'g2_unpack5.c',
    'g2_unpack6.c',
    'g2_unpack7.c',
    'gbits.c',
    'getdim.c',
    'getpoly.c',
    'gridtemplates.c',
    'int_power.c',
    'jpcpack.c',
    'jpcunpack.c',
    'misspack.c',
    'mkieee.c',
    'pack_gp.c',
    'pdstemplates.c',
    'pngpack.c',
    'pngunpack.c',
    'rdieee.c',
    'reduce.c',
    'seekgb.c',
    'simpack.c',
    'simunpack.c',
    'specpack.c',
    'specunpack.c'
    ])

env.Install(os.environ['LOCAL_LIB_DIR'], 'libgrib2c.a')

install_include = '%s/grib2c' % os.environ['LOCAL_INC_DIR']
env.Install(install_include, [
    'drstemplates.h',
    'grib2.h',
    'gridtemplates.h',
    'pdstemplates.h'
    ])

env.Alias('install', [os.environ['LOCAL_LIB_DIR'], install_include])
env.Alias('install_include', install_include)
