
import os
env = Environment(CPPPATH=[os.environ["RAL_INC_DIR"], os.environ["LOCAL_INC_DIR"], "include"], LIBPATH=os.environ["RAL_LIB_DIR"], CCFLAGS=os.environ["RAL_CCFLAGS"])
    
env.Library("stat_tools", [
  "stat_tools/stat_tools.cc"
  ]
            )

env.Install(env["LIBPATH"], "libstat_tools.a")

install_include = "%s/stat_tools" % os.environ["RAL_INC_DIR"]
env.Install(install_include, ["include/stat_tools/stat_tools.hh"])

env.Alias("install", [env["LIBPATH"], install_include])
env.Alias("install_include", install_include)





