
import os

env = Environment(
        CPPPATH=[".", os.environ["NETCDF_INC_DIR"], os.environ["HDF_INC_DIR"], os.environ["LOCAL_INC_DIR"], os.environ["RAL_INC_DIR"]], 
        CCFLAGS=os.environ["RAL_CCFLAGS"], 
        LIBPATH=[os.environ["NETCDF_LIB_DIR"], os.environ["HDF_LIB_DIR"], os.environ["LOCAL_LIB_DIR"], os.environ["RAL_LIB_DIR"], "/usr/lib"])

vdt_inc_dir = "%s/vdt4" % os.environ["LOCAL_INC_DIR"]

test_vdt_nearest_nbr = env.Program(
    "test_vdt_nearest_nbr", [
    "main.cc",
                                   ],LIBS=[
                                           "vdt4",
                                           "ANN",
                                           "m"])

env.Install(os.environ["LOCAL_BIN_DIR"], "test_nearest_nbr")
env.Alias("install", [os.environ["LOCAL_BIN_DIR"]])


