import os

# set the name of the application
program = 'roadcond_mdss'

env = Environment(
        CPPPATH=['.', os.environ['LOCAL_INC_DIR'], os.environ['NETCDF_INC_DIR'],
                 os.environ['HDF_INC_DIR'], os.environ['ZLIB_INC_DIR']], 
        LIBPATH=[os.environ['LOCAL_LIB_DIR'], os.environ['NETCDF_LIB_DIR'],
                 os.environ['HDF5_LIB_DIR'], os.environ['ZLIB_LIB_DIR']],
        CCFLAGS=os.environ['CCFLAGS'])


env.Program(
    program,[
        'bridge.cc',
        'calc_mobility.cc',
        'calc_local_time.cc',
        'calc_road_temp.cc',
        'ChemConc.cc',
        'CharacterizeStorm.cc',
        'CalcChemRate.cc',
        'Utilities.cc',
        'metro_direct.cc',
        'metro_file_io.cc',
        'parse_traffic_layer_config.cc',
        'parse_treatment_list.cc',
        'read_last_rc_file.cc',
        'read_layer.cc',
        'read_traffic.cc',
        'read_obs.cc',
        'read_wx.cc',
        'road_cond.cc',
        'RulesOfPractice.cc',
        'SiteLayerTraffic.cc',
        'snow_density.cc',
        'store_road_cond.cc',
        'main.cc'
        ],
    LIBS=[
        'log',
        'gtime',
        'nxncf',
        'ncf',
        'site_list',
        'netcdf_c++',
        'netcdf',
        'hdf5_hl',
        'hdf5',
        'z',
        'metro',
        'gfortran'
        ],
    )

env.Install(os.environ['LOCAL_BIN_DIR'], program)
env.Alias('install', os.environ['LOCAL_BIN_DIR'])
