// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
// ** Copyright UCAR (c) 1992 - 2015
// ** University Corporation for Atmospheric Research(UCAR)
// ** National Center for Atmospheric Research(NCAR)
// ** Research Applications Laboratory(RAL)
// ** P.O.Box 3000, Boulder, Colorado, 80307-3000, USA
// ** See LICENCE.TXT if applicable for licence details
// ** 2015/00/12 23:55:00 UTC
// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
////////////////////////////////////////////
// Params.cc
//
// TDRP C++ code file for class 'Params'.
//
// Code for program post_proc
//
// This file has been automatically
// generated by TDRP, do not modify.
//
/////////////////////////////////////////////

/**
 *
 * @file Params.cc
 *
 * @class Params
 *
 * This class is automatically generated by the Table
 * Driven Runtime Parameters (TDRP) system
 *
 * @note Source is automatically generated from
 *       paramdef file at compile time, do not modify
 *       since modifications will be overwritten.
 *
 *
 * @author Automatically generated
 *
 */
using namespace std;

#include "Params.hh"
#include <cstring>

  ////////////////////////////////////////////
  // Default constructor
  //

  Params::Params()

  {

    // zero out table

    memset(_table, 0, sizeof(_table));

    // zero out members

    memset(&_start_, 0, &_end_ - &_start_);

    // class name

    _className = "Params";

    // initialize table

    _init();

    // set members

    tdrpTable2User(_table, &_start_);

    _exitDeferred = false;

  }

  ////////////////////////////////////////////
  // Copy constructor
  //

  Params::Params(const Params& source)

  {

    // sync the source object

    source.sync();

    // zero out table

    memset(_table, 0, sizeof(_table));

    // zero out members

    memset(&_start_, 0, &_end_ - &_start_);

    // class name

    _className = "Params";

    // copy table

    tdrpCopyTable((TDRPtable *) source._table, _table);

    // set members

    tdrpTable2User(_table, &_start_);

    _exitDeferred = false;

  }

  ////////////////////////////////////////////
  // Destructor
  //

  Params::~Params()

  {

    // free up

    freeAll();

  }

  ////////////////////////////////////////////
  // Assignment
  //

  void Params::operator=(const Params& other)

  {

    // sync the other object

    other.sync();

    // free up any existing memory

    freeAll();

    // zero out table

    memset(_table, 0, sizeof(_table));

    // zero out members

    memset(&_start_, 0, &_end_ - &_start_);

    // copy table

    tdrpCopyTable((TDRPtable *) other._table, _table);

    // set members

    tdrpTable2User(_table, &_start_);

    _exitDeferred = other._exitDeferred;

  }

  ////////////////////////////////////////////
  // loadFromArgs()
  //
  // Loads up TDRP using the command line args.
  //
  // Check usage() for command line actions associated with
  // this function.
  //
  //   argc, argv: command line args
  //
  //   char **override_list: A null-terminated list of overrides
  //     to the parameter file.
  //     An override string has exactly the format of an entry
  //     in the parameter file itself.
  //
  //   char **params_path_p:
  //     If this is non-NULL, it is set to point to the path
  //     of the params file used.
  //
  //   bool defer_exit: normally, if the command args contain a 
  //      print or check request, this function will call exit().
  //      If defer_exit is set, such an exit is deferred and the
  //      private member _exitDeferred is set.
  //      Use exidDeferred() to test this flag.
  //
  //  Returns 0 on success, -1 on failure.
  //

  int Params::loadFromArgs(int argc, char **argv,
                           char **override_list,
                           char **params_path_p,
                           bool defer_exit)
  {
    int exit_deferred;
    if (_tdrpLoadFromArgs(argc, argv,
                          _table, &_start_,
                          override_list, params_path_p,
                          _className,
                          defer_exit, &exit_deferred)) {
      return (-1);
    } else {
      if (exit_deferred) {
        _exitDeferred = true;
      }
      return (0);
    }
  }

  ////////////////////////////////////////////
  // loadApplyArgs()
  //
  // Loads up TDRP using the params path passed in, and applies
  // the command line args for printing and checking.
  //
  // Check usage() for command line actions associated with
  // this function.
  //
  //   const char *param_file_path: the parameter file to be read in
  //
  //   argc, argv: command line args
  //
  //   char **override_list: A null-terminated list of overrides
  //     to the parameter file.
  //     An override string has exactly the format of an entry
  //     in the parameter file itself.
  //
  //   bool defer_exit: normally, if the command args contain a 
  //      print or check request, this function will call exit().
  //      If defer_exit is set, such an exit is deferred and the
  //      private member _exitDeferred is set.
  //      Use exidDeferred() to test this flag.
  //
  //  Returns 0 on success, -1 on failure.
  //

  int Params::loadApplyArgs(const char *params_path,
                            int argc, char **argv,
                            char **override_list,
                            bool defer_exit)
  {
    int exit_deferred;
    if (tdrpLoadApplyArgs(params_path, argc, argv,
                          _table, &_start_,
                          override_list,
                          _className,
                          defer_exit, &exit_deferred)) {
      return (-1);
    } else {
      if (exit_deferred) {
        _exitDeferred = true;
      }
      return (0);
    }
  }

  ////////////////////////////////////////////
  // isArgValid()
  // 
  // Check if a command line arg is a valid TDRP arg.
  //

  bool Params::isArgValid(const char *arg)
  {
    return (tdrpIsArgValid(arg));
  }

  ////////////////////////////////////////////
  // load()
  //
  // Loads up TDRP for a given class.
  //
  // This version of load gives the programmer the option to load
  // up more than one class for a single application. It is a
  // lower-level routine than loadFromArgs, and hence more
  // flexible, but the programmer must do more work.
  //
  //   const char *param_file_path: the parameter file to be read in.
  //
  //   char **override_list: A null-terminated list of overrides
  //     to the parameter file.
  //     An override string has exactly the format of an entry
  //     in the parameter file itself.
  //
  //   expand_env: flag to control environment variable
  //               expansion during tokenization.
  //               If TRUE, environment expansion is set on.
  //               If FALSE, environment expansion is set off.
  //
  //  Returns 0 on success, -1 on failure.
  //

  int Params::load(const char *param_file_path,
                   char **override_list,
                   int expand_env, int debug)
  {
    if (tdrpLoad(param_file_path,
                 _table, &_start_,
                 override_list,
                 expand_env, debug)) {
      return (-1);
    } else {
      return (0);
    }
  }

  ////////////////////////////////////////////
  // loadFromBuf()
  //
  // Loads up TDRP for a given class.
  //
  // This version of load gives the programmer the option to
  // load up more than one module for a single application,
  // using buffers which have been read from a specified source.
  //
  //   const char *param_source_str: a string which describes the
  //     source of the parameter information. It is used for
  //     error reporting only.
  //
  //   char **override_list: A null-terminated list of overrides
  //     to the parameter file.
  //     An override string has exactly the format of an entry
  //     in the parameter file itself.
  //
  //   const char *inbuf: the input buffer
  //
  //   int inlen: length of the input buffer
  //
  //   int start_line_num: the line number in the source which
  //     corresponds to the start of the buffer.
  //
  //   expand_env: flag to control environment variable
  //               expansion during tokenization.
  //               If TRUE, environment expansion is set on.
  //               If FALSE, environment expansion is set off.
  //
  //  Returns 0 on success, -1 on failure.
  //

  int Params::loadFromBuf(const char *param_source_str,
                          char **override_list,
                          const char *inbuf, int inlen,
                          int start_line_num,
                          int expand_env, int debug)
  {
    if (tdrpLoadFromBuf(param_source_str,
                        _table, &_start_,
                        override_list,
                        inbuf, inlen, start_line_num,
                        expand_env, debug)) {
      return (-1);
    } else {
      return (0);
    }
  }

  ////////////////////////////////////////////
  // loadDefaults()
  //
  // Loads up default params for a given class.
  //
  // See load() for more detailed info.
  //
  //  Returns 0 on success, -1 on failure.
  //

  int Params::loadDefaults(int expand_env)
  {
    if (tdrpLoad(NULL,
                 _table, &_start_,
                 NULL, expand_env, FALSE)) {
      return (-1);
    } else {
      return (0);
    }
  }

  ////////////////////////////////////////////
  // sync()
  //
  // Syncs the user struct data back into the parameter table,
  // in preparation for printing.
  //
  // This function alters the table in a consistent manner.
  // Therefore it can be regarded as const.
  //

  void Params::sync(void) const
  {
    tdrpUser2Table(_table, (char *) &_start_);
  }

  ////////////////////////////////////////////
  // print()
  // 
  // Print params file
  //
  // The modes supported are:
  //
  //   PRINT_SHORT:   main comments only, no help or descriptions
  //                  structs and arrays on a single line
  //   PRINT_NORM:    short + descriptions and help
  //   PRINT_LONG:    norm  + arrays and structs expanded
  //   PRINT_VERBOSE: long  + private params included
  //

  void Params::print(FILE *out, tdrp_print_mode_t mode)
  {
    tdrpPrint(out, _table, _className, mode);
  }

  ////////////////////////////////////////////
  // checkAllSet()
  //
  // Return TRUE if all set, FALSE if not.
  //
  // If out is non-NULL, prints out warning messages for those
  // parameters which are not set.
  //

  int Params::checkAllSet(FILE *out)
  {
    return (tdrpCheckAllSet(out, _table, &_start_));
  }

  //////////////////////////////////////////////////////////////
  // checkIsSet()
  //
  // Return TRUE if parameter is set, FALSE if not.
  //
  //

  int Params::checkIsSet(const char *paramName)
  {
    return (tdrpCheckIsSet(paramName, _table, &_start_));
  }

  ////////////////////////////////////////////
  // freeAll()
  //
  // Frees up all TDRP dynamic memory.
  //

  void Params::freeAll(void)
  {
    tdrpFreeAll(_table, &_start_);
  }

  ////////////////////////////////////////////
  // usage()
  //
  // Prints out usage message for TDRP args as passed
  // in to loadFromArgs().
  //

  void Params::usage(ostream &out)
  {
    out << "TDRP args: [options as below]\n"
        << "   [ -params/--params path ] specify params file path\n"
        << "   [ -check_params] check which params are not set\n"
        << "   [ -print_params [mode]] print parameters\n"
        << "     using following modes, default mode is 'norm'\n"
        << "       short:   main comments only, no help or descr\n"
        << "                structs and arrays on a single line\n"
        << "       norm:    short + descriptions and help\n"
        << "       long:    norm  + arrays and structs expanded\n"
        << "       verbose: long  + private params included\n"
        << "       short_expand:   short with env vars expanded\n"
        << "       norm_expand:    norm with env vars expanded\n"
        << "       long_expand:    long with env vars expanded\n"
        << "       verbose_expand: verbose with env vars expanded\n"
        << "   [ -tdrp_debug] debugging prints for tdrp\n"
        << "   [ -tdrp_usage] print this usage\n";
  }

  ////////////////////////////////////////////
  // arrayRealloc()
  //
  // Realloc 1D array.
  //
  // If size is increased, the values from the last array 
  // entry is copied into the new space.
  //
  // Returns 0 on success, -1 on error.
  //

  int Params::arrayRealloc(const char *param_name, int new_array_n)
  {
    if (tdrpArrayRealloc(_table, &_start_,
                         param_name, new_array_n)) {
      return (-1);
    } else {
      return (0);
    }
  }

  ////////////////////////////////////////////
  // array2DRealloc()
  //
  // Realloc 2D array.
  //
  // If size is increased, the values from the last array 
  // entry is copied into the new space.
  //
  // Returns 0 on success, -1 on error.
  //

  int Params::array2DRealloc(const char *param_name,
                             int new_array_n1,
                             int new_array_n2)
  {
    if (tdrpArray2DRealloc(_table, &_start_, param_name,
                           new_array_n1, new_array_n2)) {
      return (-1);
    } else {
      return (0);
    }
  }

  ////////////////////////////////////////////
  // _init()
  //
  // Class table initialization function.
  //
  //

  void Params::_init()

  {

    TDRPtable *tt = _table;

    // Parameter 'file1_input_var_names'
    // ctype is 'char*'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = STRING_TYPE;
    tt->param_name = tdrpStrDup("file1_input_var_names");
    tt->descr = tdrpStrDup("Core forecast variables");
    tt->help = tdrpStrDup("Only variables which are forecast in the dicast system");
    tt->array_offset = (char *) &_file1_input_var_names - &_start_;
    tt->array_n_offset = (char *) &file1_input_var_names_n - &_start_;
    tt->is_array = TRUE;
    tt->array_len_fixed = FALSE;
    tt->array_elem_size = sizeof(char*);
    tt->array_n = 19;
    tt->array_vals = (tdrpVal_t *)
        tdrpMalloc(tt->array_n * sizeof(tdrpVal_t));
      tt->array_vals[0].s = tdrpStrDup("T");
      tt->array_vals[1].s = tdrpStrDup("max_T");
      tt->array_vals[2].s = tdrpStrDup("min_T");
      tt->array_vals[3].s = tdrpStrDup("dewpt");
      tt->array_vals[4].s = tdrpStrDup("wind_u");
      tt->array_vals[5].s = tdrpStrDup("wind_v");
      tt->array_vals[6].s = tdrpStrDup("wind_speed");
      tt->array_vals[7].s = tdrpStrDup("cloud_cov");
      tt->array_vals[8].s = tdrpStrDup("visibility");
      tt->array_vals[9].s = tdrpStrDup("prob_fog");
      tt->array_vals[10].s = tdrpStrDup("prob_thunder");
      tt->array_vals[11].s = tdrpStrDup("cprob_rain");
      tt->array_vals[12].s = tdrpStrDup("cprob_snow");
      tt->array_vals[13].s = tdrpStrDup("cprob_ice");
      tt->array_vals[14].s = tdrpStrDup("prob_precip03");
      tt->array_vals[15].s = tdrpStrDup("prob_precip06");
      tt->array_vals[16].s = tdrpStrDup("prob_precip24");
      tt->array_vals[17].s = tdrpStrDup("qpf03");
      tt->array_vals[18].s = tdrpStrDup("qpf06");
    tt++;
    
    // Parameter 'file1_output_var_names'
    // ctype is 'char*'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = STRING_TYPE;
    tt->param_name = tdrpStrDup("file1_output_var_names");
    tt->descr = tdrpStrDup("Core forecast variables");
    tt->help = tdrpStrDup("Only variables which are forecast in the dicast system");
    tt->array_offset = (char *) &_file1_output_var_names - &_start_;
    tt->array_n_offset = (char *) &file1_output_var_names_n - &_start_;
    tt->is_array = TRUE;
    tt->array_len_fixed = FALSE;
    tt->array_elem_size = sizeof(char*);
    tt->array_n = 19;
    tt->array_vals = (tdrpVal_t *)
        tdrpMalloc(tt->array_n * sizeof(tdrpVal_t));
      tt->array_vals[0].s = tdrpStrDup("T");
      tt->array_vals[1].s = tdrpStrDup("max_T");
      tt->array_vals[2].s = tdrpStrDup("min_T");
      tt->array_vals[3].s = tdrpStrDup("dewpt");
      tt->array_vals[4].s = tdrpStrDup("wind_u");
      tt->array_vals[5].s = tdrpStrDup("wind_v");
      tt->array_vals[6].s = tdrpStrDup("wind_speed");
      tt->array_vals[7].s = tdrpStrDup("cloud_cov");
      tt->array_vals[8].s = tdrpStrDup("visibility");
      tt->array_vals[9].s = tdrpStrDup("prob_fog");
      tt->array_vals[10].s = tdrpStrDup("prob_thunder");
      tt->array_vals[11].s = tdrpStrDup("cprob_rain");
      tt->array_vals[12].s = tdrpStrDup("cprob_snow");
      tt->array_vals[13].s = tdrpStrDup("cprob_ice");
      tt->array_vals[14].s = tdrpStrDup("prob_precip03");
      tt->array_vals[15].s = tdrpStrDup("prob_precip06");
      tt->array_vals[16].s = tdrpStrDup("prob_precip24");
      tt->array_vals[17].s = tdrpStrDup("qpf03");
      tt->array_vals[18].s = tdrpStrDup("qpf06");
    tt++;
    
    // Parameter 'file2_input_var_names'
    // ctype is 'char*'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = STRING_TYPE;
    tt->param_name = tdrpStrDup("file2_input_var_names");
    tt->descr = tdrpStrDup("Non-verifiable variables");
    tt->help = tdrpStrDup("Variables extracted from regressor and in mod_fcst   format");
    tt->array_offset = (char *) &_file2_input_var_names - &_start_;
    tt->array_n_offset = (char *) &file2_input_var_names_n - &_start_;
    tt->is_array = TRUE;
    tt->array_len_fixed = FALSE;
    tt->array_elem_size = sizeof(char*);
    tt->array_n = 12;
    tt->array_vals = (tdrpVal_t *)
        tdrpMalloc(tt->array_n * sizeof(tdrpVal_t));
      tt->array_vals[0].s = tdrpStrDup("P_sfc");
      tt->array_vals[1].s = tdrpStrDup("T_cb");
      tt->array_vals[2].s = tdrpStrDup("T_bls");
      tt->array_vals[3].s = tdrpStrDup("T_lbls0");
      tt->array_vals[4].s = tdrpStrDup("T_lbls1");
      tt->array_vals[5].s = tdrpStrDup("T_lbls2");
      tt->array_vals[6].s = tdrpStrDup("T_lbls3");
      tt->array_vals[7].s = tdrpStrDup("snow_depth");
      tt->array_vals[8].s = tdrpStrDup("net_snow_depth");
      tt->array_vals[9].s = tdrpStrDup("cloud_low");
      tt->array_vals[10].s = tdrpStrDup("cloud_middle");
      tt->array_vals[11].s = tdrpStrDup("cloud_high");
    tt++;
    
    // Parameter 'file2_output_var_names'
    // ctype is 'char*'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = STRING_TYPE;
    tt->param_name = tdrpStrDup("file2_output_var_names");
    tt->descr = tdrpStrDup("Non-verifiable variables");
    tt->help = tdrpStrDup("Variables extracted from regressor and in mod_fcst   format");
    tt->array_offset = (char *) &_file2_output_var_names - &_start_;
    tt->array_n_offset = (char *) &file2_output_var_names_n - &_start_;
    tt->is_array = TRUE;
    tt->array_len_fixed = FALSE;
    tt->array_elem_size = sizeof(char*);
    tt->array_n = 12;
    tt->array_vals = (tdrpVal_t *)
        tdrpMalloc(tt->array_n * sizeof(tdrpVal_t));
      tt->array_vals[0].s = tdrpStrDup("P_sfc");
      tt->array_vals[1].s = tdrpStrDup("T_cb");
      tt->array_vals[2].s = tdrpStrDup("T_bls");
      tt->array_vals[3].s = tdrpStrDup("T_lbls0");
      tt->array_vals[4].s = tdrpStrDup("T_lbls1");
      tt->array_vals[5].s = tdrpStrDup("T_lbls2");
      tt->array_vals[6].s = tdrpStrDup("T_lbls3");
      tt->array_vals[7].s = tdrpStrDup("snow_depth");
      tt->array_vals[8].s = tdrpStrDup("net_snow_depth");
      tt->array_vals[9].s = tdrpStrDup("cloud_low");
      tt->array_vals[10].s = tdrpStrDup("cloud_middle");
      tt->array_vals[11].s = tdrpStrDup("cloud_high");
    tt++;
    
    // Parameter 'file2_input_blend_var_names'
    // ctype is 'char*'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = STRING_TYPE;
    tt->param_name = tdrpStrDup("file2_input_blend_var_names");
    tt->descr = tdrpStrDup("Non-verifiable variables");
    tt->help = tdrpStrDup("Variables extracted from regressor and in mod_fcst   format");
    tt->array_offset = (char *) &_file2_input_blend_var_names - &_start_;
    tt->array_n_offset = (char *) &file2_input_blend_var_names_n - &_start_;
    tt->is_array = TRUE;
    tt->array_len_fixed = FALSE;
    tt->array_elem_size = sizeof(char*);
    tt->array_n = 0;
    tt->array_vals = (tdrpVal_t *)
        tdrpMalloc(tt->array_n * sizeof(tdrpVal_t));
    tt++;
    
    // Parameter 'file2_output_blend_var_names'
    // ctype is 'char*'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = STRING_TYPE;
    tt->param_name = tdrpStrDup("file2_output_blend_var_names");
    tt->descr = tdrpStrDup("Non-verifiable variables");
    tt->help = tdrpStrDup("Variables extracted from regressor and in mod_fcst   format");
    tt->array_offset = (char *) &_file2_output_blend_var_names - &_start_;
    tt->array_n_offset = (char *) &file2_output_blend_var_names_n - &_start_;
    tt->is_array = TRUE;
    tt->array_len_fixed = FALSE;
    tt->array_elem_size = sizeof(char*);
    tt->array_n = 0;
    tt->array_vals = (tdrpVal_t *)
        tdrpMalloc(tt->array_n * sizeof(tdrpVal_t));
    tt++;
    
    // Parameter 'file2_blend_weights'
    // ctype is 'float'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = FLOAT_TYPE;
    tt->param_name = tdrpStrDup("file2_blend_weights");
    tt->descr = tdrpStrDup("Blending weights for file2 blend_var_names");
    tt->help = tdrpStrDup("size of array must be: number of blend_var_names * num_output_days * num_output_times_per_day");
    tt->array_offset = (char *) &_file2_blend_weights - &_start_;
    tt->array_n_offset = (char *) &file2_blend_weights_n - &_start_;
    tt->is_array = TRUE;
    tt->array_len_fixed = FALSE;
    tt->array_elem_size = sizeof(float);
    tt->array_n = 1;
    tt->array_vals = (tdrpVal_t *)
        tdrpMalloc(tt->array_n * sizeof(tdrpVal_t));
      tt->array_vals[0].f = 1.70141e+38;
    tt++;
    
    // Parameter 'deriv_var_names'
    // ctype is 'char*'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = STRING_TYPE;
    tt->param_name = tdrpStrDup("deriv_var_names");
    tt->descr = tdrpStrDup("Variables to retain as inputs for derived variables at  end of post proc");
    tt->help = tdrpStrDup("");
    tt->array_offset = (char *) &_deriv_var_names - &_start_;
    tt->array_n_offset = (char *) &deriv_var_names_n - &_start_;
    tt->is_array = TRUE;
    tt->array_len_fixed = FALSE;
    tt->array_elem_size = sizeof(char*);
    tt->array_n = 10;
    tt->array_vals = (tdrpVal_t *)
        tdrpMalloc(tt->array_n * sizeof(tdrpVal_t));
      tt->array_vals[0].s = tdrpStrDup("T");
      tt->array_vals[1].s = tdrpStrDup("dewpt");
      tt->array_vals[2].s = tdrpStrDup("wind_u");
      tt->array_vals[3].s = tdrpStrDup("wind_v");
      tt->array_vals[4].s = tdrpStrDup("wind_speed");
      tt->array_vals[5].s = tdrpStrDup("qpf03");
      tt->array_vals[6].s = tdrpStrDup("prob_precip03");
      tt->array_vals[7].s = tdrpStrDup("cprob_snow");
      tt->array_vals[8].s = tdrpStrDup("cprob_rain");
      tt->array_vals[9].s = tdrpStrDup("cprob_ice");
    tt++;
    
    // Parameter 'conf_deriv_var_names'
    // ctype is 'char*'
    
    memset(tt, 0, sizeof(TDRPtable));
    tt->ptype = STRING_TYPE;
    tt->param_name = tdrpStrDup("conf_deriv_var_names");
    tt->descr = tdrpStrDup("Confidence variables to retain as inputs for derived variables at  end of post proc");
    tt->help = tdrpStrDup("");
    tt->array_offset = (char *) &_conf_deriv_var_names - &_start_;
    tt->array_n_offset = (char *) &conf_deriv_var_names_n - &_start_;
    tt->is_array = TRUE;
    tt->array_len_fixed = FALSE;
    tt->array_elem_size = sizeof(char*);
    tt->array_n = 1;
    tt->array_vals = (tdrpVal_t *)
        tdrpMalloc(tt->array_n * sizeof(tdrpVal_t));
      tt->array_vals[0].s = tdrpStrDup("T");
    tt++;
    
    // trailing entry has param_name set to NULL
    
    tt->param_name = NULL;
    
    return;
  
  }
