
import os

env = Environment(
        CPPPATH=[".", os.environ["NETCDF_INC_DIR"], os.environ["HDF_INC_DIR"], os.environ["LOCAL_INC_DIR"], os.environ["RAL_INC_DIR"]], 
        CCFLAGS=os.environ["RAL_CCFLAGS"], 
        LIBPATH=[os.environ["NETCDF_LIB_DIR"], os.environ["HDF_LIB_DIR"], os.environ["LOCAL_LIB_DIR"], os.environ["RAL_LIB_DIR"]] )

simulate_probe = env.Program(
    "simulate_probe", [
    "arguments.cc",
    "config_reader.cc",
    "main.cc",
    "process.cc",
    "vdt_road_segment_datasets.cc",
    "get_time.cc",
    "simulate_probe.cc",
    "simulate_probe_config.cc"
        
                                   ],LIBS=[
                                           "libconfig++",
                                           "log",
                                           "rwx",
                                           "vdt4",
                                           "ANN",
                                           "netcdf_c++4",
                                           "netcdf_c++",
                                           "netcdf",
                                           "hdf5_hl",
                                           "hdf5",
                                           "z",
                                           "Proj4Wrap",
                                           "proj",
                                           "boost_filesystem",
                                           "boost_system",
                                           "stat_tools",
                                           "m"])

env.Install(os.environ["LOCAL_BIN_DIR"], "simulate_probe")
env.Alias("install", [os.environ["LOCAL_BIN_DIR"]])


