# For c-shell users: in you .cshrc set the following
# 
# on motown:
# setenv LOCAL_ROOT /d1/local
# setenv LOCAL_INC_DIR ${LOCAL_ROOT}/include
# setenv LOCAL_LIB_DIR ${LOCAL_ROOT}/lib
# setenv LOCAL_BIN_DIR ${LOCAL_ROOT}/bin
#
# setenv RAL_INC_DIR /usr/include
# setenv RAL_LIB_DIR /usr/lib
# setenv RAL_CCFLAGS "-Wall -g -O -static"

import os

env = Environment(
        CPPPATH=[".", os.environ["LOCAL_INC_DIR"],os.environ["RAL_INC_DIR"]], 
        CCFLAGS=os.environ["RAL_CCFLAGS"], 
        LIBPATH=[os.environ["LOCAL_LIB_DIR"], os.environ["RAL_LIB_DIR"]] )

vdt_inc_dir = "%s/vdt4" % os.environ["LOCAL_INC_DIR"]

probe_message_dataset_manager = env.Program(
    "probe_message_stats", [
    "arguments.cc",
    "config_reader.cc",
    "main.cc",
    "process.cc"
                                   ],LIBS=["libconfig++",
                                           "log",
                                           "gdal",
                                           "vdt4",
                                           "netcdf_c++4",
                                           "netcdf_c++",
                                           "netcdf",
                                           "hdf5_hl",
                                           "hdf5",
                                           "z",
                                           "boost_filesystem",
                                           "boost_system",
                                           "stat_tools"])
